### ISSUE TITLE
开启插件后 github 合并代码解决冲突问题

### ISSUE THREAD

**Issue by caixiaomao** [EnixCoda/Gitako#100]
开启插件后 github 合并代码解决冲突，标记状态为已解决后页面会刷新，导致解决冲突无效，关闭插件后则正常，麻烦看看这个问题，谢谢啦。另：感谢提供这么好用的插件。

**Comment by EnixCoda** [comment]
感谢！已修复代码，请期待下一版本发布！

**Comment by caixiaomao** [comment]
好的 非常感谢

**Comment by EnixCoda** [comment]
Fixed in `v2.4.1`
