### ISSUE TITLE
gitee 提示 Access Denied & 未显示文件夹

### ISSUE THREAD

**Issue by dxhuii** [EnixCoda/Gitako#101]
Access Denied
Gitako needs access token to read this project. Please setup access token in the settings panel below.

版本：2.4.0
chrome 版本：版本 86.0.4240.198

**Comment by EnixCoda** [comment]
应该是触发了 Gitee 的 API 访问频率限制。

可以在这里创建 Token ，勾选 `projects`

https://gitee.com/profile/personal_access_tokens/new

**Comment by dxhuii** [comment]
> 应该是触发了 Gitee 的 API 访问频率限制。
> 
> 可以在这里创建 Token ，勾选 `projects`
> 
> https://gitee.com/profile/personal_access_tokens/new

好了，已经正常了，谢谢。

**Comment by dxhuii** [comment]
还有一个问题 @EnixCoda 现在没有目录了如图

![1.png](https://i.loli.net/2020/11/13/HE8saUdqo4NViK2.jpg)

**Comment by EnixCoda** [comment]
看了下是因为 Gitee 移除了文件接口响应中的文件夹的相关数据，要再适配一下。会在近日更新

再次感谢反馈！
