### ISSUE TITLE
Ctrl+MouseClick does NOT open the file links in new tab.

### ISSUE THREAD

**Issue by jinliming2** [EnixCoda/Gitako#102]
Version: 2.4.2

支持按住 ctrl 键时，点击文件链接可以在新标签页中打开。

**Comment by EnixCoda** [comment]
Hi @jinliming2 , thank you for filing this issue!

Gitako is not supposed to block the default keys to open file links in new tab, which is
- on macOS: command + click
- on Windows: ctrl + click

I can verify it is working on Windows 10 + Chrome + Gitako v2.4.2.

It would be a bug if it doesn't work for you. Please provide more info, e.g. OS, browser. Or disable other extensions to see if there were conflicts.

**Comment by jinliming2** [comment]
I'm using Linux (Gentoo, i3-wm, Kernel 5.4.72), Google Chrome Version 88.0.4315.5 (Official Build) dev (64-bit).
Seems like this is a bug. It won't work on the Code page but works on the Pull requests page.
似乎这是一个 bug。在“Code”页面按住 ctrl 键时不能在新标签页打开，但在“Pull requests”页面可以。

**Comment by EnixCoda** [comment]
@jinliming2 Thank you. I've confirmed the issue on Ubuntu.

**Comment by EnixCoda** [comment]
Fixed in v2.4.3. Tested on Ubuntu 20.04.
