### ISSUE TITLE
[Feature] Add support for hub.fastgit.org (a mirror of github.com)

### ISSUE THREAD

**Issue by ludoux** [EnixCoda/Gitako#103]
哈喽， [FastGit](http://fastgit.org/) 是一个对 GitHub 的镜像站，在国内访问有时候会稍微比源站快一点，不知道作者能不能也支持一下呢（不过假如因为隐私安全性等因素考虑不支持也ok的啦）
插件很棒 XD

**Comment by EnixCoda** [comment]
你好，感谢使用 Gitako！

我看了一下 FastGit，它似乎没有提供可靠的 API 反代地址，Web 功能也阉割了（不支持登陆）。可能无法很好地适配，很遗憾。也许等日后完善了可以再考虑 :)
