### ISSUE TITLE
how to use pjax to prevent page loading.

### ISSUE THREAD

**Issue by chouglesaud** [EnixCoda/Gitako#105]
can someone explain to me how this works? @EnixCoda 
how did you achieve the clicking behavior like GitHub? clicking on the file link doesn't reload the page.

**Comment by chouglesaud** [comment]
I know what is pjax. I wanna know how you did it.

**Comment by EnixCoda** [comment]
Hi @chouglesaud , glad to share what I know with you!

`clicking on the file link doesn't reload the page` is achieved by registering the `click` event on the anchor elements and prevent its default behavior. For example, in react:

```jsx
<a href="/" onClick={e => e.preventDefault}>Click won't reload</a>
```

And then comes PJAX and it does its work.

**Comment by chouglesaud** [comment]
thanks for the quick response. @EnixCoda 
``And then comes PJAX and it does its work.``
how actually this work. if possible can you explain by little example
because Github has `pjax:start` `pjax:end` `pjax:click` and several other events. is `pjax:click` the solution?

**Comment by chouglesaud** [comment]
I look into your code
which code is responsible for that event?
```
import { Config, Pjax } from 'pjax-api'
import * as React from 'react'
import { useEvent } from 'react-use'
import { useProgressBar } from './useProgressBar'

const config: Config = {
  areas: [
    // github
    '.repository-content',
    '[data-pjax="#js-repo-pjax-container"]',
    '.page-content',
    // gitee
    '#git-project-content',
  ],
  update: {
    css: false,
  },
  fetch: {
    cache(path) {
      return path
    },
  },
  form: 'form:not(form)', // prevent blocking form submissions
  fallback(target, reason) {
    // prevent unexpected reload
  },
}

export function usePJAX() {
  // make history travel work
  React.useEffect(() => {
    new Pjax({
      ...config,
      filter() {
        return false
      },
    })
  }, [])

  const progressBar = useProgressBar()
  useEvent('pjax:fetch', progressBar.mount, window)
  useEvent('pjax:unload', progressBar.unmount, window)

  return React.useCallback(url => {
    Pjax.assign(url, config)
  }, [])
}
------------------------------------------------------ is this ---------------------------------------------
export function useOnPJAXDone(callback: () => void, both = true) {
  useEvent('pjax:ready', callback, document)
  if (both) useEvent('pjax:end', callback, document) // emit by GitHub
} -----------------------------------------------------------------------------------------------------------
```

**Comment by EnixCoda** [comment]
Yes, that is where Gitako listens to PJAX events from its self and GitHub.

When clicking on file links of Gitako, the PJAX progress is triggered from the internal `pjax-api` lib, instead of the one came with GitHub. The `pjax-api` emits events like `pjax:fetch`, `pjax:ready` but excluding those GitHub would emit, e.g. `pjax:end` `pjax:start`.

And what Gitako cares about are `pjax:ready` and `pjax:end` events, when they are triggered, Gitako will decorate the page and its sidebar.

The `Pjax.assign(url, config)` statement is where Gitako invokes `pjax-api`, i.e. `And then comes PJAX and it does its work.`

**Comment by chouglesaud** [comment]
thanks, now I'm getting it.
but one more last thing. @EnixCoda 

> And what Gitako cares about are `pjax:ready` and `pjax:end` events, when they are triggered, Gitako will decorate the page and its sidebar.

these events are from pjax-api?
and when we click on link `Pjax.assign(url, config)` executed.

**Comment by EnixCoda** [comment]
> these events are from pjax-api?

Not both. `pjax:ready` is from `pjax-api` while `pjax:end` is from GitHub. Listening to `pjax:ready` makes sense obviously. While listening to `pjax:end` might not be that intuitive. Let me explain.

Sometimes, when clicking on elements of GitHub, e.g. the `issues` tab, the page redirects with GitHub's PJAX. Although it is not triggered by Gitako, it also need to know that page content has changed try to do necessary work, for example, the `auto expand` feature needs to toggle Gitako when redirections happen.

> when we click on link Pjax.assign(url, config) executed.

Exactly.

**Comment by chouglesaud** [comment]
> Sometimes, when clicking on elements of GitHub, e.g. the issues tab, the page redirects with GitHub's PJAX. Although it is not triggered by Gitako, it also need to know that page content has changed try to do necessary work, for example, the auto expand feature needs to toggle Gitako when redirections happen.

I get it :) auto-expanding listen `pjax:end` when necessary.

thanks for the help :+1:

**Comment by EnixCoda** [comment]
:) Feel free to ask again if get more questions
