### ISSUE TITLE
Gitako breaks browser history of GitHub

### ISSUE THREAD

**Issue by jinliming2** [EnixCoda/Gitako#106]
Gitako: v2.4.2
Chrome Canary 89.0.4333.0
OS: Windows 10 (20H2) / Linux (Gentoo, Kernel 5.4.72, x11, i3-wm)

Steps to reproduce:
1. Goto "Commits" Page of a repository in GitHub. Ex: https://github.com/EnixCoda/Gitako/commits/develop
2. Click an item in the commit list, go to file diff page A.
3. Click the "Back" button on the browser, back to commit list page.
4. Click another item in the commit list, go to file diff page B.
5. Click the "Back" button on the browser.

At step 5, expected to go back to the commit list page. Actually, I got the URL of commit list page in the address bar but shown the file diff page A.

Everything works fine when disabling Gitako.

1. 进入任意仓库的“Commits”提交列表页。比如：https://github.com/EnixCoda/Gitako/commits/develop
2. 点击任意的提交记录，进入文件差异页面 A。
3. 点击浏览器的“返回”按钮，退回到提交列表页。
4. 点击另一条提交记录，进入文件差异页面 B。
5. 点击浏览器的“返回”按钮。

在第 5 步，本应返回到提交列表页面。但是实际情况是，地址栏中的 URL 是提交列表页的地址，但是页面却显示的是文件差异页面 A。

禁用 Gitako 后恢复正常。

**Comment by EnixCoda** [comment]
Thank you for the feedback! This is a known issue and I am working on a new version of PJAX to fix this.

Thanks for pointing it out anyway :)

**Comment by EnixCoda** [comment]
Fixed most cases of the issue in v2.4.3. It should not bother users anymore except in rare cases I suppose :P
