### ISSUE TITLE
为什么我在gitako上输入gitee访问令牌后，就报Can't connection to gitee. github依然可以使用

### ISSUE THREAD

**Issue by wardseptember** [EnixCoda/Gitako#107]

**Comment by EnixCoda** [comment]
请确保你提供的令牌已被赋予 Projects 权限。
如果赋予后仍报错，麻烦提供一下报错时的浏览器 console 截图，谢谢

**Comment by wardseptember** [comment]
@EnixCoda 现在又好了，可能是访问gitee次数太多了。

**Comment by EnixCoda** [comment]
如果令牌是正确的，Gitee 应该撤去访问次数限制才对。可能是 Gitee API 临时故障。

**Comment by turbidsoul** [comment]
@EnixCoda 我在firefox上也有这个问题，我在控制台上看到的是请求的连接的branchName的前后加了一个空格。
![图片](https://user-images.githubusercontent.com/554941/137865308-2a4f7dbd-c070-4bbb-8bd5-40191d448648.png)
在刷新之后就好了，再次点击依然是这样
