### ISSUE TITLE
Causing page unresponsive when opening a repository with a large amount of files

### ISSUE THREAD

**Issue by Emrys365** [EnixCoda/Gitako#108]
When opening https://github.com/microsoft/DNS-Challenge with Gitako installed on Chrome, I found it caused the whole page unresponsive (cannot select or right click), and itself also couldn't show any files in the list.

**Comment by EnixCoda** [comment]
Hi @Emrys365 Thanks for feedback!

I caught no issues using Gitako in this repo. Tested on macOS, Ubuntu and Windows 10. Gitako is supposed to function smoothly even in very large repos. Please help me identify the problem with these steps:
- disable Gitako and access the repo again to see if the problem still exists
- provide more information about your environment, including OS, network condition(using proxy or being behind GFW), etc

**Comment by Emrys365** [comment]
Hi @EnixCoda, thank you for your suggestions!

I checked the installed extensions, and finally found that it was actually caused by another old extension (Insight.io for Github). After disabling it, it is now working for me. So it is not related to Gitako. Nice extension!
