### ISSUE TITLE
[Feature] Dark Mode

### ISSUE THREAD

**Issue by 333fred** [EnixCoda/Gitako#109]
I know that https://github.com/EnixCoda/Gitako/issues/29 was previously closed with a recommendation to use stylus/dark reader/other extension, but GitHub is now rolling out a native dark mode, meaning that those extensions are no longer necessary. Given that, native support for a dark mode would be a nice addition.

**Comment by umaim** [comment]
Gitako on GitHub Dark

![image](https://user-images.githubusercontent.com/9652227/101569490-8bd75e80-3a0f-11eb-88dc-589879fa599b.png)

**Comment by EnixCoda** [comment]
Thanks for the issue. It makes sense to provide dark mode styles now as GitHub has implemented its native dark mode! I'll work on it.

BTW, How could this issue get so many 👍 in such short time?! 🤯

**Comment by ghost** [comment]
> BTW, How could this issue get so many 👍 in such short time?! 🤯

People switched to dark mode in GitHub, opened Gitako and then immediately scrolled down to Request Feature and... here we are. Took 30 seconds. At least it should be easy to prioritize features like this 😄

**Comment by hengstchon** [comment]
I did some hack to the css file to make it dark mode. If you guys want to use it before the official dark mode release, feel free to generate the temporary dark mode version.

Procedures:

```bash
git clone https://github.com/hengstchon/Gitako.git
cd Gitako
git checkout dark-mode-css
make dark-mode
 ```

Now you will get the `Gitako.zip` file in the `dist` directory.
Then  just drag it to the chrome extension page.

Preview:

![Screenshot 2020-12-10 at 08 16 44](https://user-images.githubusercontent.com/7352093/101734560-c4834080-3ac0-11eb-8891-f685ab70e0af.png)

**Comment by EnixCoda** [comment]
@hengstchon Thanks for the help.

But I do not recommend most users to do so, as they'll need to disable Gitako to use your version, which might stop them from get the future updates(the dark mode support) in time.

I do understand that your experiences degraded these days. Don't worry! The next release is on the way, you should be able to get the update today or tomorrow.

**Comment by aurexav** [comment]
> @hengstchon Thanks for the help.
> 
> But I do not recommend most users to do so, as they'll need to disable Gitako to use your version, which might stop them from get the future updates(the dark mode support) in time.
> 
> The next release is on the way, you should be able to update it today or tomorrow. Don't worry!

If the update is available today, that's awesome!

**Comment by EnixCoda** [comment]
The dark mode support has been released, please update Gitako to `v2.5.0` to get the best GitHub experience. 😎

And let me know if there are any other problems remaining.

Note: The review process of Edge always take long time, about 1 week. If you are using Gitako on Edge, I'd suggest you install Gitako from Chrome web store instead of Edge's.

**Comment by EnixCoda** [comment]
The changes made for this feature is more than I expected.

Will wait for https://github.com/primer/css/pull/1131 to be merged and https://github.com/primer/components to provide a official theme for dark mode so that I can remove those hacky code from Gitako's codebase.

**Comment by spences10** [comment]
Looks like it's already landed??

![image](https://user-images.githubusercontent.com/234708/101797543-139d9580-3b02-11eb-8f5a-d72f3441df61.png)

Good job 👍

**Comment by h4wwk3ye** [comment]
I think the whitish color being used by GitHub look easier to read than the blue color you are using.
This is on Firefox.
![Screenshot 2020-12-10 221856](https://user-images.githubusercontent.com/24487030/101802721-c6d3b200-3b35-11eb-9bb7-049b6bedb367.png)

**Comment by 333fred** [comment]
I actually like the contrast from the main list, though I can see the arguments for going the other direction.

**Comment by qiuyuhang** [comment]
Two issues:
- Hovering on the scroll bar is still in light mode.
- Toggle button should also be in dark mode (maybe).

After all, it's a very cool extension. I ❤️ this.

**Comment by EnixCoda** [comment]
Yes, Gitako's file tree should pick the same color scheme as GitHub's.  Here are the previews after changing the colors.

## Light
![image](https://user-images.githubusercontent.com/7480839/101877798-8a519600-3bc9-11eb-9f36-5034ef81b21f.png)

### Light - hover
![image](https://user-images.githubusercontent.com/7480839/101877888-a7866480-3bc9-11eb-936a-2ec9508221f0.png)

## Dark
![image](https://user-images.githubusercontent.com/7480839/101877916-b3722680-3bc9-11eb-8427-9b66bb42c266.png)

### Dark - hover
![image](https://user-images.githubusercontent.com/7480839/101878033-da305d00-3bc9-11eb-82b9-277e40110357.png)

---
And answering to @qiuyuhang :
> Hovering on the scroll bar is still in light mode.

It seems to only occur to Chrome on macOS and when you set scrollbar to be hidden when not hover. It works well on Firefox. And I found no styles related to the scrollbar of document body. So I suspect it is a bug of Chrome.

> Toggle button should also be in dark mode (maybe).

Maybe not. :P The toggle button(Gitako logo) is designed to work in both light and dark mode.

**Comment by EnixCoda** [comment]
Released v2.5.1, in which the color of the links are corrected.

And closing this issue as most users have updated to v2.5.0+

**Comment by uchihamalolan** [comment]
@EnixCoda 
Love your work <3
Now that GitHub has release a variant of Dark Mode (i.e `Dark Dimmed`). Can this also be included?

<img width="1440" alt="Screenshot 2021-03-30 at 09 03 46" src="https://user-images.githubusercontent.com/24520586/112929893-f6cfb100-9136-11eb-820e-5c78c720f844.png">

**Comment by EnixCoda** [comment]
@uchihamalolan Thanks for telling me about this! It should not take too much effort to adapt the new theme, please stay tuned :)

**Comment by EnixCoda** [comment]
Added better support for color modes in `v2.7.3`. All theme modes ✖️ all color modes should be properly applied.

**Comment by ForsakenHarmony** [comment]
Hey, I'm using the dark high contrast theme and the extension sidebar is in light mode with some broken elements

![](https://i.hrmny.sh/bptT7FBMjH.png)

**Comment by EnixCoda** [comment]
@ForsakenHarmony Is the `dark high contrast theme` provided by GitHub? I don't see it in [GitHub appearance settings](https://github.com/settings/appearance).

If it is provided by some other extensions, I recommend you to use the official dark theme. :)

**Comment by ForsakenHarmony** [comment]
@EnixCoda it is official, but it might be a preview (don't see an indication though)

![Screenshot_20210722-065424_Firefox_Nightly~2](https://user-images.githubusercontent.com/8845940/126591608-c138a373-e7f0-4236-9344-6ab46ec7ebc5.png)

**Comment by EnixCoda** [comment]
@ForsakenHarmony Oh, I found it in the preview features! The new version is on the way! Thank you very much!

**Comment by ForsakenHarmony** [comment]
@EnixCoda thanks for the fix 🙏
