### ISSUE TITLE
Compress empty folders inside another empty folders

### ISSUE THREAD

**Issue by TheRafaelFarias** [EnixCoda/Gitako#122]
When a project has a tree like: `src/command/subcommand/file.type`

Right now is rendered:

```
-> src
   -> command
       -> subcomando
           -> subcommand
              -> file.type
```

Rendering like this is an issue in smaller monitors (or even in big monitor depending on how deep the tree is)

Would be much better just render:

```
src/command/subcommand
    -> file.type
```

This is quite useful in Java projects where a lot of folders inside folders is used

**Comment by EnixCoda** [comment]
Hi @TheRafaelFarias 

Gitako already has such exact feature implemented.

Please confirm if the `Compress singleton folder` has been enabled.

![image](https://user-images.githubusercontent.com/7480839/105947148-90310700-60a3-11eb-8fe3-08b648026179.png)

**Comment by TheRafaelFarias** [comment]
Oh, I hadn't enabled that. Worked, thanks
