### ISSUE TITLE
[Feature] VS Code like code outline view using tree-sitter plugins

### ISSUE THREAD

**Issue by Himujjal** [EnixCoda/Gitako#123]
Hi. I regularly explore code in github. It would be awesome if we could show a code outline view like [vs code outline-view](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view)
We can use [web-tree-sitter](https://www.npmjs.com/package/web-tree-sitter) along with tree-sitter-grammars for different extensions.

Features:
- Easy to navigate code-bases and also long `markdown` files.
- Downloading tree-sitter-grammars (wasm files) dynamically for each extension the user has visited.
- Web workers + WASM based parser to avoid slowdown. 
- The outline view can be put below the original file-tree in an accordion. Similar to how VS Code does in its sidebar.

I can help you guys with this feature. I have good experience with tree-sitter

**Comment by EnixCoda** [comment]
Thank you @Himujjal  This feature looks useful!

But I think it might be too much for Gitako. Maybe it will be better to develop another browser extension for this feature?

**Comment by Himujjal** [comment]
You sure about that? A simple accordion could maybe do the trick as showing only files at first and the user can click the accordion to show the outline.

And as I mentioned, it wouldnt take much resources with webworkers and wasm either.

Should I proceed? I could spin up an alpha in a week.

The problem with separate extension is that the  space will already be occupied by gitako.

**Comment by EnixCoda** [comment]
Gitako has no features of analyzing the content of files now.

In my point of view, `show a code outline view` is one of the features related to analyzing file contents, others including
- jump to symbol
- code folding
- syntax highlighting
- etc.

As you can see, it is another field of tooling and there are a lot of things we can do if had the ability to analyze file contents. With that in mind, I believe it will be better to have another extension to do these specifically. If you are worried about the UI, maybe the outline component could float aside the file content. It should not be a big issue anyway.

What do you think?

**Comment by Himujjal** [comment]
Yes. I was thinking of making it minimal.

In github, the code is __read-only__. Which means, code-folding and syntax-highlighting can be taken off this feature. We only need a JSON/object which is the outline of the code.

The preview will be something like this. We don't need to get through every other node in the AST of the code.
```bash
> globalVariableA
> classNameA
  > fieldA
  > functionA
> globalFunctionA
> globalVariableB
```

Let's say some user clicks on `classNameA`, the user is directed to something like https://github.com/EnixCoda/Gitako/blob/develop/src/env.ts#L3. See that `#L3` at the end.
We only need the _line-numbers_ (which tree-sitter provides by default).

Regarding the execution. Here are the steps:
1. Launch a web-worker. In the web-worker:
2. Check in the service-worker cache if the `wasm` file for the particular language is already downloaded. If not, download and cache the `wasm` file for the language (tree-sitter grammars are all in C and super performant) 
3. Fetch code through [https://raw.githubusercontent.com](https://raw.githubusercontent.com/EnixCoda/Gitako/develop/src/env.ts) links.
4. Parse code through tree-sitter using webassembly. Get the outlines, the line numbers and the type of the outline node.
5. Pass this data to the main thread and display it in the sidebar using the type to generate the relevant icon/color. (say class has another icon, say function has another)

That should be more than enough. This will be super useful for markdown files. Users could simply use both the current Gitako sidebar and the outline view to create/view awesome documentation/(doc books) like this:

https://doc.rust-lang.org/stable/book/

**Comment by EnixCoda** [comment]
But code-folding is quite necessary according to my use experience and I am already using [such extension](https://chrome.google.com/webstore/detail/github-code-folding/lefcpjbffalgdcdgidjdnmabfenecjdf) for that.

The details of jump to symbol and execution progress you introduced is very clear. However, by saying *too much for Gitako*, I mean it will be not only too much code to maintain but also too many features for a single extension to provide. I try to be as cautious as possible when adding features to Gitako. Let users combine extensions to match their needs.

> This will be super useful for markdown files.

Check out [this extension](https://github.com/jawil/GayHub), it not only has file tree but also renders ToC for markdown files. Might be what you are looking for. :)

**Comment by Himujjal** [comment]
I checked both the extensions. First one does serve the purpose of code-folding. Second one is kinda doesn't give me outline view for markdown though.

you mind if I fork this repo and maintain my own extension. Loading too many extensions is not something I prefer though.

**Comment by EnixCoda** [comment]
The outline of markdown is on the right side.

![image](https://user-images.githubusercontent.com/7480839/106379874-ebd3fb00-63e9-11eb-9b03-031dc40da008.png)

Feel free to have your own fork! Gitako is using MIT license.
