### ISSUE TITLE
Copy file button is duplicated when navigating back

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#130]
![image](https://user-images.githubusercontent.com/44045911/113478303-a8b20900-94ba-11eb-83cc-2ffa06cc3013.png)

Steps to reproduce:

1. Open a file with "Copy file" button, for example https://github.com/EnixCoda/Gitako/blob/develop/Makefile
2. Click a PJAXed page, for example "History"
3. Navigate back
4. Notice the duplicate button

**Comment by EnixCoda** [comment]
Thank you!

**Comment by EnixCoda** [comment]
Fixed, will be included in the next release, `v2.8`.
