### ISSUE TITLE
Follow current branch

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#131]
Not sure if this should be categorized into feature request or bug report, but Gitako doesn't follow the current branch when switching.

To reproduce:

1. Open a branch (or commit, or any git ref), for example https://github.com/EnixCoda/Gitako/tree/1a0272e3bf5a2e978f24843c84d87f1d3cf9c94b
2. Click the code tab to go to the default (in the example's case `develop`) branch
3. Notice Gitako still shows file tree for the previous branch

**Comment by EnixCoda** [comment]
Wow, thank you very much!

I was trying to reproduce an issue caught indicating this unmatched situation but did not realize the entry would be the `code` tab.

**Comment by EnixCoda** [comment]
Fixed, will be included in the next release, ~`v2.8`~ `v2.8.1`.

**Comment by EnixCoda** [comment]
Fixed in `v2.8.1` and the release progress is going on.

Not a satisfying fix to myself. Will refactor the related module in `v3` for a better experience.
