### ISSUE TITLE
Support new GitHub token format

### ISSUE THREAD

**Issue by klauern** [EnixCoda/Gitako#132]
With the [new format for github tokens](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/), it appears gitako is struggling to identify it:

![image](https://user-images.githubusercontent.com/4735/114053646-c255a680-9854-11eb-8b69-9df19661b44b.png)

**Comment by klauern** [comment]
I'd create with OAuth, but then I would be unable to use this within my organization's repositories without granting access to the entire company.

**Comment by EnixCoda** [comment]
@klauern Thank you!

**Comment by EnixCoda** [comment]
Done, will be included in the next release, `v2.8`.
