### ISSUE TITLE
Question: Option to hide Gitako by default

### ISSUE THREAD

**Issue by wfxr** [EnixCoda/Gitako#133]
Thanks for this nice tool! I hava used it for a long time.

However can we add a option to support hiding the sidebar by default? Sometimes the sidebar occupies too much space when the browser window is narrow.

**Comment by kidonng** [comment]
Just toggle `Auto expand` off and you are good to go:

![image](https://user-images.githubusercontent.com/44045911/114293477-e4575f00-9ac8-11eb-824e-aacba65b2dc1.png)

**Comment by EnixCoda** [comment]
Thank you @kidonng :)

BTW, the long-waited float mode for sidebar is about to arrive.

**Comment by wfxr** [comment]
Aha! It's already there! Thank you @kidonng .

**Comment by wfxr** [comment]
> BTW, the long-waited float mode for sidebar is about to arrive.

I'm not very clear about what it is but it sounds cool! Looking forward to seeing it soon.

**Comment by kidonng** [comment]
> I'm not very clear about what it is but it sounds cool! Looking forward to seeing it soon.

https://github.com/EnixCoda/Gitako/issues/98#issuecomment-812860207
