### ISSUE TITLE
Icon missing for BUILD.bazel

### ISSUE THREAD

**Issue by FareesHussain** [EnixCoda/Gitako#137]
BAZEL Icon is missing for BUILD.bazel and WORKSPACE but available for `.bazelrc` and `.bzl`
![image](https://user-images.githubusercontent.com/54740946/117235005-a6d5bf80-ae43-11eb-9804-f4cafadf033f.png)

If possible I would like to work on this

**Comment by EnixCoda** [comment]
Hi @FareesHussain 

The map from extension to icons is not **manually** managed in this repository but generated from the [vscode-icons repo](https://github.com/vscode-icons/vscode-icons). You might need to submit the issue there.

**Comment by EnixCoda** [comment]
But the icons have not been updated for a while. I'll run the generating progress to update them before the next non-patch release.

Thanks for reminding me! :)

**Comment by FareesHussain** [comment]
> But the icons have not been updated for a while. I'll run the generating progress to update them before the next non-patch release.
> 
> Thanks for reminding me! :)

@EnixCoda Shall I create a PR for bazel icons or wait for the release

**Comment by FareesHussain** [comment]
@EnixCoda I think vscode-icons include the Bazel icon for `.bazel`
maybe this requires a version update

**Comment by EnixCoda** [comment]
Updates for icons will be shipped soon.

![image](https://user-images.githubusercontent.com/7480839/127759131-d9b7ee32-e690-4d17-9fce-890e21f7387b.png)
