### ISSUE TITLE
Disable copy snippet button by default

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#141]
GitHub added native code block copy buttons: https://twitter.com/natfriedman/status/1391862005095485440

You can see them here: https://github.com/wting/autojump

I was wondering if Gitako should drop it in the future :) (Not now though, because GitHub enterprise users may still need Gitako's copy button)

**Comment by EnixCoda** [comment]
Glad to see GitHub introducing such a feature, which looks exactly how it has been implemented in Gitako. LOL

I may update the default state of the feature to disabled while not removing it to allow usages in the enterprise version as well as other platforms.

**Comment by kidonng** [comment]
> I may update the default state of the feature to disabled while not removing it to allow usages in the enterprise version as well as other platforms.

That's exactly what I want!

**Comment by EnixCoda** [comment]
`v3.0.0` is out with this change :D

**Comment by EnixCoda** [comment]
Seems to not working properly for new users.

**Comment by EnixCoda** [comment]
Fixed in `v3.1.1`
