### ISSUE TITLE
edge extended outdated!!

### ISSUE THREAD

**Issue by crper** [EnixCoda/Gitako#144]
## chrome

![image](https://user-images.githubusercontent.com/8272877/119784427-c622b280-bf00-11eb-8670-23df11c4b367.png)

## Edge
![image](https://user-images.githubusercontent.com/8272877/119784333-ac816b00-bf00-11eb-93ba-628a621c1926.png)

**Comment by EnixCoda** [comment]
Thank you! Will upload the latest version.

**Comment by EnixCoda** [comment]
The release experience of Edge add-ons store is way worse than other stores :(

ETA of release: 14 days.

**Comment by crper** [comment]
@EnixCoda 
![tempImage1622601927330](https://user-images.githubusercontent.com/8272877/120416388-a4f21400-c38f-11eb-98a4-02cba0d16c09.gif) But there are more and more people using edge. Our front-end development is also using edge as the main browser more and more.

**Comment by EnixCoda** [comment]
@crper Yes, Edge is quite good in lots of aspects. I personally use it sometimes too. I mean their team should put more resource on supporting developers of Edge add-ons so that all 3 sides benefit.

**Comment by EnixCoda** [comment]
Finally passed Edge store review just now.

**Comment by yidasanqian** [comment]
meet same problem
