### ISSUE TITLE
Manjaro: Scrolling with mouse wheel is not captured when the extension is not pinned

### ISSUE THREAD

**Issue by farzadmf** [EnixCoda/Gitako#153]
When the extension is not pineed, and I hover over it to show up, if I then use the mouse wheel to scroll (say through the code files), the sidebar disappears and the scroll happens on the GitHub page itself.

Even if the GitHub page is _not_ scrollable (everything is in view), using the mouse wheel would cause the extension to disappear

**Comment by EnixCoda** [comment]
@farzadmf Thanks for submitting the issue!

Could you provide more info like your OS, browser, and their versions?

Gitako works well according to my test on {Windows, macOS} x {Chrome, Edge, Firefox}.

**Comment by farzadmf** [comment]
Hey @EnixCoda 

Thank you for the reply,

I'm not at my desk right now, but my OS is Manjaro Linux and I'm using Google Chrome (should be the latest version, which I think is 92 🤔)

Let me know if you need more info or anything else to help

**Comment by EnixCoda** [comment]
Hi @farzadmf 
I gave another try on Ubuntu 20.04, Chrome 91 (91 is the latest stable version I could get and Chrome Canary says it is unavailable to Linux), which is the only Linux VM I have on my machine, but still failed to reproduce. So I suppose it should be a rare issue that only happens on Manjaro or some other Linux OSs. But I do appreciate it that you submitting this issue, thank you very much!

If any other users encounter this problem in other environments, please let me know. :)

**Comment by farzadmf** [comment]
Hi @EnixCoda 

I tried to create a GIF to show what's happening for me (thought it might be useful):
- I first hover over Gitako and it's shown
- Then I scroll using the wheel: the Gitako tree is scrolled down, but it disappears
- Then I have over it without scrolling to show that hide/show works
- Then again I scroll using the wheel: this time as well, the Gitako tree is scrolled up, but it also disappears
- The last time where you see the Github page scrolling is where Gitako has scrolled to the end and I use the wheel when my mouse is on Gitako.

Thank you

![gitako-scroll](https://user-images.githubusercontent.com/5768792/121812758-2a4eb180-cc37-11eb-97e0-23a470729a9d.gif)

**Comment by EnixCoda** [comment]
I see. I tried to install Manjaro but had some troubles and failed. :(

Please try other browsers or alternatives to Gitako. I can see Octotree in your screenshot, hope it works well!

**Comment by farzadmf** [comment]
Gitako is, IMO, much more promising and more pleasant to work with, and this issue that I opened is not a show stopper for Gitako (I can pin it or use a shortcut to open/close)

I just opened this issue because I thought it's a very small detail that can be fixed in an already cool extension.

But I totally feel you; if you can't reproduce it, how can you know what's wrong 🙃

I'll update here in case I see new clues 🙂

**Comment by EnixCoda** [comment]
Thank you for trusting! I totally understand that and really appreciate it that you submit this issue. I'm very thankful!

Let's keep this issue open.

**Comment by farzadmf** [comment]
Sure, 👍

Sounds good to me

**Comment by farzadmf** [comment]
@EnixCoda It's been QUITE a while for this; does closing as completed means it was fixed?

Sorry in advance as I don't think I'll be able to reproduce the issue after more than 2 years 😆

**Comment by EnixCoda** [comment]
@farzadmf I happened to got access to a PC running Manjaro and I did not reproduce this issue on it. I believe this has been fixed from Manjaro's side :)

**Comment by farzadmf** [comment]
Great @EnixCoda ; always nice when issues resolve themselves 😆
