### ISSUE TITLE
Repository link should include current branch

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#158]
Current the link just points to the repository without considering the branch:

![image](https://user-images.githubusercontent.com/44045911/122666082-bd5e8d00-d1dd-11eb-9d6c-0c8ead2847af.png)

**Comment by EnixCoda** [comment]
Thanks! @kidonng 

It is designed to work in this way. As you can see the repository title on the GitHub page also ignores the branch.

![image](https://user-images.githubusercontent.com/7480839/122666618-08c66a80-d1e1-11eb-992c-7bf57dd156f0.png)

To redirect to the branch's homepage, users can click on the `Code` tab button.

![image](https://user-images.githubusercontent.com/7480839/122666650-390e0900-d1e1-11eb-8f4f-e44e9fb11773.png)

But it might be a good idea to make the branch name clickable and point to the branch's homepage as the function of the `Code` is not very intuitive. :D

**Comment by kidonng** [comment]
> To redirect to the branch's homepage, users can click on the `Code` tab button.

I know how GitHub works natively, but I consider Gitako to be  **an extension to the Code tab** and have the same behavior. Also you have to scroll to the top/press <kbd>g</kbd> <kbd>c</kbd> in order to access it which is inconvenient somehow.

> But it might be a good idea to make the branch name clickable and point to the branch's homepage as the function of the `Code` is not very intuitive. :D 

That's an alternative solution.

**Comment by chawyehsu** [comment]
Not for voting no for this issue, but I always use this link to fastly navigate to the repository homepage when GitHub's headers/tabs are scrolled out of the viewport.

For a better UX, I would suggest changing the branch label in Gitako to be a clickable link which navigating to the branch's homepage, i.e.:

![20210629102925](https://user-images.githubusercontent.com/5764917/123727860-e6a9a800-d8c4-11eb-9e7b-f280b0e4fbd1.png)

This would keep both of the benefits.

**Comment by EnixCoda** [comment]
Done in `v3.3.0`, will release soon.
