### ISSUE TITLE
Preserve folder expansion state when searching

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#159]
Suppose I have some folders expanded:

![image](https://user-images.githubusercontent.com/44045911/122845914-52c16480-d337-11eb-9844-2007da0e8f9c.png)

And make a search:

![image](https://user-images.githubusercontent.com/44045911/122845923-57861880-d337-11eb-86e5-cb39afa318fc.png)

Clear the search, the expansion state is gone:

![image](https://user-images.githubusercontent.com/44045911/122845954-6371da80-d337-11eb-9d9c-59ba0647004e.png)

**Comment by EnixCoda** [comment]
Thanks. I'll consider it carefully. 🤔

**Comment by EnixCoda** [comment]
Done in `v3.4.0`, thank you for the suggestion!
