### ISSUE TITLE
Folder expansion state is mistakenly restored when making a navigation

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#160]
Suppose I'm in modules/config/i18n.nix:

![image](https://user-images.githubusercontent.com/44045911/122846133-c95e6200-d337-11eb-9fa0-e6545b1ccd43.png)

Then I fold the folders:

![image](https://user-images.githubusercontent.com/44045911/122846159-d713e780-d337-11eb-9782-0c5f22620ec1.png)

Navigate to doc/default.nix, and notice previously folded folders is restored to unfolded:

![image](https://user-images.githubusercontent.com/44045911/122846250-062a5900-d338-11eb-829f-429da48f7426.png)

**Comment by EnixCoda** [comment]
Thank you! :D

**Comment by kidonng** [comment]
> Thank you! :D

You are welcome! Hope one day I can contribute code in addition to issues :)

**Comment by EnixCoda** [comment]
Fixed in `v3.3.0`, will release soon.
