### ISSUE TITLE
Fix the copy button

### ISSUE THREAD

**Issue by roythearsonist** [EnixCoda/Gitako#167]
There are two instead of one, please fix this

**Comment by EnixCoda** [comment]
Gitako started providing copy snippet buttons before GitHub did. Now GitHub has provided the same feature so Gitako's is not required anymore for github.com but it is preserved as Gitako is a cross-platform extension(also works for Gitee, Gitea, etc).

This feature should be disabled by default for github.com now. You can also disable it via the settings panel (Settings -> More -> Copy Snippet Button). :)

**Comment by roythearsonist** [comment]
Uh no the extension itself creates two copy buttons, but ok

**Comment by EnixCoda** [comment]
Oh, then it would be great if you could provide the steps to produce this issue. Thank you!

BTW, I am curious about how you found out there are two buttons. If there were 2, one should overlay onto another completely.

**Comment by roythearsonist** [comment]
Steps to reproduce: 
1. Go to a copyable file (I found it on svgs, don't know about others)
2. There is a copy button next to the raw button and to the left.

I'll send screenshots when I'm on my pc again

**Comment by roythearsonist** [comment]
Forgot about this issue, here's a screenshot
![image](https://user-images.githubusercontent.com/81673375/128101449-02ca89ea-01bb-4ab8-ad3c-01684085e462.png)

**Comment by EnixCoda** [comment]
Thank you. I don't see the `<>` and 📄 buttons on my side. Are they provided by some other extensions?

**Comment by roythearsonist** [comment]
I think its because its a svg, so you can view the image and the source

**Comment by EnixCoda** [comment]
I see, I can reproduce it now!

**Comment by roythearsonist** [comment]
Ok, have fun

**Comment by EnixCoda** [comment]
Fixed in `v3.4.0`!

**Comment by roythearsonist** [comment]
Thanks
