### ISSUE TITLE
Question: Why need Authentication information ?

### ISSUE THREAD

**Issue by ksdputra** [EnixCoda/Gitako#169]
This is a stupid question. And I dont know where to ask the developers unless in this github issue.

Why do Gitako need to collect Authentication information (at least in chrome)? Is it related to some of Gitako functionalities?

<img width="1411" alt="Screen Shot 2021-08-05 at 09 08 51" src="https://user-images.githubusercontent.com/86584588/128275617-64e5d6bb-3ecc-4300-aeac-230a3df42e2b.png">

**Comment by EnixCoda** [comment]
Thank you for this issue!

Gitako requires user to provide access token, via manual input or OAuth, to access private repository or get rid of GitHub's API limit. And that is what `Authentication information` indicates.

This does not mean Gitako would collect other sensitive data from your account.

**Comment by ksdputra** [comment]
Thanks for answering. I am a newbie in this kind of thing. And want to know more. 😊

Talking about api limit. In my private repo, it asked for Authentication Token to access and github's api limit, but for public repo like yours, Gitako does not ask for the token. Is it different limit between public repo and private repo?

And some pretty similar tools does not need Authentication Information (based on their Privacy practices section) to access my private repo. Is it because Gitako use different approach, or those other tools are not honest about their privacy practices?

**Comment by EnixCoda** [comment]
Maybe the official docs about [authentication](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#authentication) and  [API rate limiting](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) can help answer these questions.

I am curious about those _similar tools_ , could you list some of them so I can checkout the way they work?

**Comment by ksdputra** [comment]
Thanks !

The one that I still use alongside with Gitako, but the filetree are only appears in PR, is [Better Pull Request for GitHub](https://chrome.google.com/webstore/detail/better-pull-request-for-g/nfhdjopbhlggibjlimhdbogflgmbiahc). It does not ask me for Authentication in private repo.

I cant say any other than Gitako is an amazing tools. I only use this for 3 days, but it helped me to surf source code in github much better 😍

**Comment by EnixCoda** [comment]
Because it only works in PR's files tab, where all data it needs are already provided in DOM, hence it does not need to request any other data from GitHub API. But Gitako is different, it provides PR file tree even if you are not in the files tab, which allows users to know which files are changed easier.

Thank you for your appreciation! :D
