### ISSUE TITLE
No icon for haxe

### ISSUE THREAD

**Issue by roythearsonist** [EnixCoda/Gitako#172]
I tried looking at files with the .hx extension, and it gave me the default icon. Please update this to the right one

**Comment by roythearsonist** [comment]
Here's the svg code for the icon
```xml
 <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path d="M16,5.5,5.5,16,16,26.5,26.5,16,16,5.5" style="fill:#f68712"/><path d="M2,2,16,5.5,5.5,16,2,2" style="fill:#fab20b"/><path d="M30,2,26.5,16,16,5.5,30,2" style="fill:#f47216"/><path d="M30,30,16,26.5,26.5,16,30,30" style="fill:#f25c19"/><path d="M2,30,5.5,16,16,26.5,2,30" style="fill:#f89c0e"/><path d="M16,5.5,2,2H9l7,3.5" style="fill:#fbc707"/><path d="M16,5.5,30,2H23L16,5.5" style="fill:#fbc707"/><path d="M16,26.5,30,30H23l-7-3.5" style="fill:#f68712"/><path d="M16,26.5,2,30H9l7-3.5" style="fill:#f25c19"/><path d="M5.5,16,2,30V23l3.5-7" style="fill:#fff200"/><path d="M5.5,16,2,2V9l3.5,7" style="fill:#fff200"/><path d="M26.5,16,30,2V9l-3.5,7" style="fill:#f1471d"/><path d="M26.5,16,30,30V23l-3.5-7" style="fill:#f1471d"/></svg>
```

**Comment by EnixCoda** [comment]
Hi @theblobscp 

The icons are not maintained by Gitako self but imported from [vscode-icons](https://github.com/vscode-icons/vscode-icons), please submit the issue there. Thank you :)

**Comment by roythearsonist** [comment]
I used the icon from their repo. Its just not on yours

**Comment by EnixCoda** [comment]
@theblobscp I don't see `.hx` in their [supported file icons](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles)

**Comment by roythearsonist** [comment]
yeah, but they still have a icon for it anyway

**Comment by EnixCoda** [comment]
@theblobscp Gitako generates the icon map from that vscode-icon wiki page. `.hx` will be supported if they list it on that page.

**Comment by roythearsonist** [comment]
I learned you need to install the haxe extension for it to work. So its really your choice

**Comment by EnixCoda** [comment]
I don't understand. Which haxe extension?

I found that `.hx` was [once supported in the vscode-icons](https://github.com/vscode-icons/vscode-icons/pull/178/files) and has been removed nowadays.

---

And sorry, it is not a choice of Gitako.

**Comment by roythearsonist** [comment]
There's an official haxe extension by the haxe foundation. If you install it, the haxe icon shows up.
