### ISSUE TITLE
Navbar doesn't change to "Code" tab

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#173]
When clicking the links in Gitako while in a tab other than "Code", the webpage doesn't change to "Code" tab:

https://user-images.githubusercontent.com/44045911/131352511-d00459e8-6dba-4db4-8cf0-33554f7634cb.mov

**Comment by EnixCoda** [comment]
Thank you! This is a known but not logged issue.

If the redirection is triggered by Gitako, it is not aware of the DOM status of GitHub, thus won't manipulate the style of the navbar.

Hope GitHub will try to update the style when `pjax:end` event is dispatched. This is the only way Gitako communicates with GitHub for now.

**Comment by kidonng** [comment]
> Hope GitHub will try to update the style when `pjax:end` event is dispatched.

[GitHub does update the style when `pjax:end` fired](https://github.com/sindresorhus/refined-github/issues/4782#issuecomment-919701204) but it seems `pjax-api` doesn't preserve the required `meta` tags.

**Comment by EnixCoda** [comment]
Fixed in `v3.5.1`

Thank you very much!
