### ISSUE TITLE
Document build instructions and make it portable

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#176]
Gitako as a browser extension is awesome, but the project itself is quite a hassle to work with.

- No documentation on build instructions. Just running `yarn` is not enough, I have to run `make`.

  Gitako should provide clear documentation on how to contribute to the project (or at least how to build it), instead of letting people figure it out on their own.

- Non-portable. Uses `Makefile` which requires a *nix environment and certain programs (like `zip`) to be present. npm scripts directly set environment instead of using `cross-env`.

  Gitako is a Node.js project and it should be as portable across different OS as possible. Not everyone is seasoned enough to know how to translate those commands into their environment.

- Inappropriate assumptions. Fortunately I develop on macOS, so I don't have serious issues with above points, ~~but this line fails because I don't use SSH with GitHub:~~

  https://github.com/EnixCoda/Gitako/blob/69efa5bcdc997b07a072fbc06502cbdc3b3dffd7/Makefile#L5

  ~~And it should have been using `https` anyway since it's not something private you have to use SSH to authenticate with.~~ This is fixed now.

**Comment by EnixCoda** [comment]
Thank you. I really appreciate your enthusiasm for participating in this project!

I am aware of these issues. And you should have noticed that there are no contribution instructions in this project. Currently, Gitako is my personal project, mainly driven by my own ideas and developed by myself. I made it open source to earn trust from users, as it is a tool that asks for personal access tokens. And It is designed to be lightweight, without too many features. Users should choose another tool if they have heavier requirements. So I think carefully every time when adding new features. For now, I can handle most of the development work. But I do appreciate it if anyone stands out to do so!

I'll do what you have advised when I decide to hand it off to the community.

**Comment by EnixCoda** [comment]
Added contributing.md (except for Windows dev support, no plan of that)
