### ISSUE TITLE
New colorblind themes aren't well supported

### ISSUE THREAD

**Issue by jcready** [EnixCoda/Gitako#183]
See https://github.blog/changelog/2021-09-29-colorblind-themes-beta/

When the dark colorblind theme is enabled in GitHub settings the Gitako sidebar panel uses a light/white color scheme.

It looks like it could be fixed with just an additional case for `data-dark-theme="dark_protanopia"` in [/src/styles/themes.scss](https://github.com/EnixCoda/Gitako/blob/2542ccbeb7/src/styles/themes.scss)

**Comment by EnixCoda** [comment]
Thank you for letting me know about this!

It seems that GitHub has updated the CSS variables available in DOM recently, I may update their references as well and check if any color in use has been deprecated.

**Comment by kidonng** [comment]
FYI:

- https://primer.style/design/foundations/color
- https://togithub.com/refined-github/refined-github/pull/4970#pullrequestreview-787379009

**Comment by EnixCoda** [comment]
Supported in `v3.5.1`

Special thanks to @kidonng , the links are very helpful!
