### ISSUE TITLE
Cache the file list

### ISSUE THREAD

**Issue by trustin** [EnixCoda/Gitako#196]
It will be even nicer if Gitako caches the file list in the local storage, so that it doesn't have to retrieve the complete file list every time a page is loaded. It can be fairly expensive when a PR contains a large number of files. We could maybe first fetch the latest commit ID and load the file list from the local cache if the commit ID didn't change?

**Comment by EnixCoda** [comment]
Hi @trustin 

GitHub API has implemented a good cache mechanism and the PJAX calls from Gitako are cached, including the ones for file list. Saving those into local storage may not provide significant improvements.

![image](https://user-images.githubusercontent.com/7480839/147376522-6879f28d-1bf4-4476-a79e-d888f0c6e20b.png)
