### ISSUE TITLE
Support for enterprise-hosted GitHub instances

### ISSUE THREAD

**Issue by tavyandy97** [EnixCoda/Gitako#200]
Hey!
Amazing extension and saves a lot of time. However, when I tried opening it on a enterprise-hosted GitHub instance it did not work. I assume due to the permissions being limited to certain URL patterns. The pattern for the URL I wanted support for would be something like `*github.*.com` (eg `github.company-name.com`).

Thank You

**Comment by EnixCoda** [comment]
Hi @tavyandy97 

Please check out https://github.com/EnixCoda/Gitako/wiki/Use-in-GitHub-enterprise-and-other-sites

If it still does not work, please let me know.
