### ISSUE TITLE
Icons for Nunjucks files missing

### ISSUE THREAD

**Issue by pexeixv** [EnixCoda/Gitako#206]

**Comment by EnixCoda** [comment]
Hi @pexeixv 

What specific Nunjucks files did you find missing icons? I tried to find some on GitHub and they have proper icons (the `.nunj` files).
![image](https://user-images.githubusercontent.com/7480839/153353740-a033271f-8ecd-43be-ada9-991f1cec9f22.png)

Icons support of Gitako is inherited from https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles
You can submit issues there if it should support more Nunjucks file extension names.

**Comment by pexeixv** [comment]
Nunjucks uses the `.njk` extension as well. Sorry for not mentioning that.
![image](https://user-images.githubusercontent.com/68476117/154002141-2be7ed9f-c3de-46d8-8e6a-9deddcc5d283.png)

**Comment by EnixCoda** [comment]
Thanks!

It looks like `njk` was excluded from vscode-icons. https://github.com/vscode-icons/vscode-icons/issues/1819
It depends on language ID service to recognize `.njk` as Nunjucks files. That service is from vscode, not implemented in vscode-icons. I may implement that in Gitako if there are more important icons missing.
