### ISSUE TITLE
Can you add support for subpath

### ISSUE THREAD

**Issue by darrenwjlau** [EnixCoda/Gitako#207]
I hosted my Gitea on https://darrenapi.cloud.libraryofcode.org/gitea/

and I accessed a repo on https://darrenapi.cloud.libraryofcode.org/gitea/Discord-bot/discord-bot

and the extension take the path https://darrenapi.cloud.libraryofcode.org and username gitea

shouldn't it be taking https://darrenapi.cloud.libraryofcode.org/gitea as path and discord-bot as username

**Comment by EnixCoda** [comment]
Hi @mickeydarrenlau 

I did not expect such cases of hosting gitea under subpaths. AFAIK, hosting at root of a standalone domain is a better practice. I'm afraid supporting such usages is not what Gitako would do. I'm sorry about that.
