### ISSUE TITLE
Include a screenshot preview in readme

### ISSUE THREAD

**Issue by xxchan** [EnixCoda/Gitako#212]
First thanks! Your plugin is super helpful!

But there aren't any images in README and marketplace, so I didn't know how it looks like at the beginning.(Actually I didn't even know what it is used to do😓)

So I think including a screenshot will be a good idea and attract more potential users.

**Comment by xxchan** [comment]
Oh sorry, there are demos in the marketplace. I missed them 😅

**Comment by EnixCoda** [comment]
@xxchan  Thank you anyway, I really appreciate your help!
