### ISSUE TITLE
Repository name should be PJAXed

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#214]
A small nuance, but GitHub does have the repository name PJAXed, so should Gitako:

<img width="231" alt="Screen Shot 2022-02-20 at 18 26 32" src="https://user-images.githubusercontent.com/44045911/154838313-254e6846-98f4-4e16-acfe-8e4806b539f5.png">

**Comment by EnixCoda** [comment]
Do you have an example of name in sidebar not matching the name in GitHub content?

Gitako scans page content on `pjax:end` and updates the title via react render. It is an anti-pattern to update DOM nodes rendered by react via GitHub's PJAX because it can be reverted when react renders next time.

**Comment by kidonng** [comment]
Sorry if I didn't make it clear, I'm rephrasing it now:

In #158 we decided the sidebar header should have direct mappings to GitHub's header:

<img width="488" alt="Screen Shot 2022-02-24 at 16 52 39" src="https://user-images.githubusercontent.com/44045911/155491153-2954a541-5f5c-4995-83cf-9a49fe7e206e.png">

The branch name is fine since it indeed triggers PJAX just like the "Code" tab button, but the repository name doesn't while GitHub's does.

**Comment by EnixCoda** [comment]
I see. Will implement that.
