### ISSUE TITLE
GitHub private API endpoints which doesn't require token

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#216]
Just FYI, these are some endpoints to list files used by GitHub that does not require a token. You may be interested in adding them as fallback solutions.

# "Go to file" endpoint

Namely `/owner/repo/tree-list/treeID`

```js
branch = 'main' // specify a branch
htmlRes = await fetch(`${location.pathname.split('/').slice(0, 3).join('/')}/find/${branch}`)
html = await htmlRes.text()

template = document.createElement('template')
template.innerHTML = html;
src = template.content.querySelector('virtual-filter-input').getAttribute('src') // Obtain treeId

listRes = await fetch(src, {
  headers: {
    'x-requested-with': 'XMLHttpRequest'
  }
})
list = await listRes.json()
```

Problems:

- Require firing an extra request to get the [`treeId`](https://github.com/gitbucket/gitbucket/blob/4abd363f6276201425eff4e1c82f3fbb64234fad/src/main/twirl/gitbucket/core/repo/find.scala.html#L25))

# Command palette endpoint

Namely `/command_palette/files?scope=subjectID`

```js
// Alternative: `document.querySelector('command-palette-token[data-type="repository"]').dataset.id`
id = document.querySelector('#command-palette-pjax-meta-data').dataset.subjectId
listRes = await fetch(`https://github.com/command_palette/files?scope=${id}`, {
  headers: {
    'x-requested-with': 'XMLHttpRequest'
  }
})
list = await listRes.json()
```

Problems:

- Only provide results for the default branch
- Require cookies

**Comment by EnixCoda** [comment]
Thanks, good to know that.
