### ISSUE TITLE
Preserve folder expansion state when changing search mode

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#217]
Like #159, but this time the state is reset when changing search mode:

https://user-images.githubusercontent.com/44045911/155490249-1efe7aa4-af00-414b-8a13-0e5d56cf16d8.mov

Note since #159 has been fixed, this issue only happens when the search field is empty.

**Comment by EnixCoda** [comment]
Thanks! It should not reset. Will fix it in the next release.
