### ISSUE TITLE
Switching to other pages doesn't stop file list from loading

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#218]
To reproduce:

1. Open a PR, e.g. https://github.com//nice-registry/all-the-package-repos/pull/41
2. Notice Gitako starts to load file list
3. Before it finishes loading, click "Code" tab
4. File list keeps loading and show up despite the browser already being at "Code" tab

<img width="635" alt="image" src="https://user-images.githubusercontent.com/44045911/156778175-a3c35563-00ab-416f-afe9-279e9ef04112.png">

**Comment by EnixCoda** [comment]
Reproduced after trying for few times. Thanks.
