### ISSUE TITLE
GitHub native Pull Request File Tree

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#219]
GitHub just announced [Pull Request File Tree](https://github.com/github/feedback/discussions/12341) feature preview and its feature set is overlapping Gitako's:

![](https://user-images.githubusercontent.com/2503052/156570120-574a6f58-75fa-4cf8-af1a-12fb78cc021b.png)

As this is just a feature preview, things are not set yet, but I would like to raise some concerns:

- Gitako should prevent itself from auto expanding if GitHub's native file tree is opened
- Just like #216, Gitako can make use of existing info on the page instead of calling the slower API.
- Maybe enhance GitHub's file tree or even integrate with it

**Comment by MikeAndrson** [comment]
I'm having the same issue. Gitako seems to be overriding GitHub's new Pull Request File Tree feature. It's all good when I disable Gitako

**Comment by EnixCoda** [comment]
> Gitako should prevent itself from auto expanding if GitHub's native file tree is opened

Agreed. Shipped in `v3.6.2`.

> Just like https://github.com/EnixCoda/Gitako/issues/216, Gitako can make use of existing info on the page instead of calling the slower API.

~Of course.~

After taking another thought on this, I decide not to apply this change immediately.

> Maybe enhance GitHub's file tree or even integrate with it

I think the diff icons color should match to GitHub's. Do you have more suggestions?

**Comment by EnixCoda** [comment]
Aligned icons' color with GitHub's.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/7480839/179459613-3e8830f9-08d3-4491-bf7b-ba6ee423ef33.png">
