### ISSUE TITLE
github enterprise site admin header bar obscures the top of gitako popout

### ISSUE THREAD

**Issue by nheath** [EnixCoda/Gitako#220]
![image](https://user-images.githubusercontent.com/1778613/157336138-0aa00cd0-8f5f-475b-a02e-718fb5bb3f52.png)

(PR title removed)

**Comment by EnixCoda** [comment]
@nheath Thank you for this issue. I cannot reproduce it in my GitHub Enterprise. But it looks like that the `> Version 3.3.3` label is from another extension, is it?

Please provide more info to help me investigate:
1. Does this also happen to repos on github.com? (if the other extensions is also enabled for github.com)
2. Could you retry without other extensions enabled?

Thanks!

**Comment by nheath** [comment]
I think there is some confusion, and I probably should have been more clear in my description. The issue is specifically with github enterprise, if you are a "Site Administrator"; it adds a header across the top of all pages, showing the current gihub version (thats where the version tag comes from), as well as some statistics, and a link to administrative functions for the current page. The full toolbar looks like this:

![image](https://user-images.githubusercontent.com/1778613/160443516-30192580-53a6-4721-afc0-1b0ffab46098.png)

I understand this will be difficult to test, if you dont have a GHE instance with administrative access, though I believe you can download a machine image and set up a trial instance. Let me know if i can further clarify, or help with information to troubleshoot

**Comment by EnixCoda** [comment]
I see, thank you for clarifying!

I'll try set up a trail instance.

**Comment by EnixCoda** [comment]
Wait, it would be great if you could help inspect the z-index of the admin header. I believe that would be enough for fixing this.

If you are using Chrome/Edge,
1. Right-click on the page, choose `Inspect` to open the devTools panel.
2. Click on the top-left icon in the devTools panel
3. Click on the admin header to select it (I was selecting the navbar in the screenshot)
4. Input `z-index` in the filter of `Styles` tab
5. Check out what `z-index` it has been set.

![image](https://user-images.githubusercontent.com/7480839/160638399-1d3be1bb-9c0d-480d-9d29-4d673fa6d906.png)

Note: `1.` is not shown in the screenshot

**Comment by nheath** [comment]
The z-index of the admin toolbar is 9999. For reference, the relevant styles are:
```css
.stats-ui-enabled .server-stats {
    position: relative;
    z-index: 9999;
    display: block;
}

.server-stats {
    display: none;
    background-color: #161818;
}
```

 I applied the straight forward fix of a higher z-index on `.gitako-side-bar`, and this "worked" but noticed a few things:

- The element doesnt have a `position` property set, and did not work initially. `position: relative;` fixed.
- These fixes should probably also be applied to `#gitako-logo-mount-point`
    -  I'm not sure of the intended location of the mount point (i thought i recalled it being like ~20% down the page on the left). For me, its in the upper left corner, so is also behind the admin bar.
    -  Given the mount point is always visible, if setting a high z-index, be aware of what it might hide; in my placement, setting a higher z-index obscures the admin bar.
    -  This may be ok, as no parts of the admin bar in that location are functional,  but figured a heads up was good.

**Comment by EnixCoda** [comment]
Thank you @nheath This helps me a lot!

Perhaps the `z-index` rule could be applied to `.gitako-side-bar-body-wrapper`, which is already positioned as `fixed` and has `z-index` set. You can find the rule like this:

![image](https://user-images.githubusercontent.com/7480839/161881087-73759e0a-3fa4-430c-826b-ad1babc549fd.png)

If you don't mind, please help me verify if changing `z-index` of it from `1000` to `9999` or `10000` works. Thank you again!

**Comment by nheath** [comment]
I think that communicating the situation is getting a little bit complicated, so I will try to be especially clear.

First off, I can confirm that applying `z-index: 10000` to `.gitako-side-bar-body-wrapper` does fix the issue. 

However, I appear to have a secondary issue:

Looking at the source, I see that an _element style_ for `.gitako-toggle-show-button-wrapper` is calculated to provide a `top` offset. My element has an offset of 0, which presumably comes from this code. 
https://github.com/EnixCoda/Gitako/blob/9b86021a0fbe1440e0a20340cdf6adae500bde89/src/components/ToggleShowButton.tsx#L18-L20

![image](https://user-images.githubusercontent.com/1778613/161886491-29dac936-4210-48b6-9588-2cf2c2781743.png)

As a result, the toggle button is **also** behind the admin header, and cannot be used to show the sidebar in the first place. I notice this also has a `z-index` of 1000, and can confirm that setting it to 10000 does render it over the admin header. 

I would suggest you should apply the `z-index` changes to both elements.

Lastly, it also appears to be a bug that the `top` offset is zero in the first place. That may be related to the admin header, or be a completely unrelated "local" problem. I will try to do a bit more diagnosis, and either reply to this issue, create a new issue, or hack up locally, at your preference.

**Comment by nheath** [comment]
Well, im out of my depth debugging the issue with incorrect offset. I'm not familiar with react, and trying to debug a minified chrome extension is near impossible :) 

It's worth noting this only happens on github enterprise. the offset on github.com is correct.

I can see it's effectively loading `toggleButtonVerticalDistance` from config; setting a breakpoint in that function looks like its returning 0. 

https://github.com/EnixCoda/Gitako/blob/9b86021a0fbe1440e0a20340cdf6adae500bde89/src/components/ToggleShowButton.tsx#L25
![image](https://user-images.githubusercontent.com/1778613/161889205-46e5606f-6102-468f-9fdc-fce9fe6037e8.png)

I didn't see an option in the "gear menu"; hopefully I'm missing something obvious, and i'll leave it at that for now.

Thanks for the help

**Comment by EnixCoda** [comment]
I see. It is very clear, thanks! I'll set `z-index` on both elements.

For the offset issue, have you ever (accidentally) dragged the icon to the top? In normal cases, it can be dragged in persistent mode. But I did drag it once accidentally in float mode.

Its default value is `124`. Browser windows cannot be resized to `0` height. So dragging is the only way to set its offset to `0`.
https://github.com/EnixCoda/Gitako/blob/9b86021a0fbe1440e0a20340cdf6adae500bde89/src/utils/config/helper.ts#L59

You can drag it downwards and see if its offset will be reset to verify.

**Comment by nheath** [comment]
Its possible I had dragged it and reset the setting--thanks for the hint, I didnt realize one could do this to update the setting.
