### ISSUE TITLE
Support new themes - Tritanopia, Protanopia & Deuteranopia

### ISSUE THREAD

**Issue by btvoidx** [EnixCoda/Gitako#226]
Github added two new colorblind themes, and the dark one confuses the extension.
![image](https://user-images.githubusercontent.com/37330718/164040501-e2865b3e-4203-4364-8311-904fa3796e24.png)
![image](https://user-images.githubusercontent.com/37330718/164040717-208367c0-df58-4d1a-a86b-287d616a4603.png)

**Comment by EnixCoda** [comment]
Thanks for letting me know. Will add support for them.
