### ISSUE TITLE
The newest version of "Gitako" has been disabled

### ISSUE THREAD

**Issue by JunQu** [EnixCoda/Gitako#232]
hi, thanks for making this plugin,it's very helpful to me.
probably from yesterday, it was suddenly automatically disabled by the Chrome browser,I actually just used it on GitHub，should me accept these permissions?

chrome version: Version 100.0.4896.127 (Official Build) (x86_64)

<img width="428" alt="image" src="https://user-images.githubusercontent.com/39846309/166087895-5c58d646-56c8-4b53-b7f5-083127873fc9.png">

**Comment by EnixCoda** [comment]
Hi @JunQu 

Sorry for the inconvenience. This is because a permission change that `gitako.now.sh` has been replaced with `gitako.enix.one`. Details in #223

**Comment by JunQu** [comment]
@EnixCoda i got it after read #223 , i should re-enable Gitako.
thank you for fix it well.

**Comment by EnixCoda** [comment]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/7480839/169467970-3e225a83-1c0d-41e4-839b-e5192e553483.png">

Updating permission is harmful. There is a peak of uninstallation due to it.

**Comment by EnixCoda** [comment]
Closing as most users have upgraded and re-enabled Gitako.
