### ISSUE TITLE
Memory leak in large pull requests

### ISSUE THREAD

**Issue by 333fred** [EnixCoda/Gitako#235]
When I open https://github.com/dotnet/roslyn/pull/61565 or other similarly-sized PRs with this extension enabled, I see memory usage in the tab increase both quickly and regularly, at a rate of ~5 MB/sec (in approximately 5 second bursts), until the tab is eventually killed due to out of memory issues. When I disable Gitako, the leak goes away and the memory usage of the tab is stable.

**Comment by EnixCoda** [comment]
Thanks, @333fred 

After a quick investigation, the reason is that Gitako would query PR file list endlessly because of unexpected responses from GitHub.

I'll release a patch for the issue soon.

**Comment by EnixCoda** [comment]
Fixed in `v3.7.1`, now Gitako can load PRs even 10x larger than https://github.com/dotnet/roslyn/pull/61565 , e.g. https://github.com/dotnet/roslyn/pull/61070
