### ISSUE TITLE
chrome upgrade sidebar not display

### ISSUE THREAD

**Issue by CreatorMetaSky** [EnixCoda/Gitako#239]
chrome version: 103.0.5060.53
when click source code file, the sidebar will not auto expand, but refresh the browser tab, it will work again.

**Comment by lycheezhou** [comment]
我也遇到了这个问题

**Comment by Ray-Eldath** [comment]
same on 103.0.5060.53 (Manjaro Linux). and the gitako can't always show now. when jump from one file to another, sometime Gitako would completely not shown up. has to refresh the tab then.

**Comment by eshimischi** [comment]
Same issue, Brave Browser (latest update is chrome: 103.0.5060.53) on MacOS

**Comment by CreatorMetaSky** [comment]
i think it's Github native pjax container problem, nothing to do with platforms.
i try rollback the code before #177, use the `pjax-api`, it's ok.

finally, i temporarily use version 3.4.1, because it not use the github native pjax.

**This is a temporary solution to the sidebar does not show, but some new features can't be used, look forward to solving the problem** 

@EnixCoda

**Comment by EnixCoda** [comment]
Thanks for reporting this issue. I can reproduce it on my Chrome 102 as well. GitHub might have changed the way its PJAX works. Let me take a deeper look later...

**Comment by chawyehsu** [comment]
https://github.com/refined-github/refined-github/pull/5720

Some other GitHub extensions have broken at the same time. This might help with fixing the issue.

**Comment by EnixCoda** [comment]
@chawyehsu Thank you, that is a good reference to the fix!

---

I cannot reproduce the issue this time. I've tried different browsers, all good.

Perhaps GitHub has rollback temporarily?

**Comment by CreatorMetaSky** [comment]
yeah, it's fixed by github.

**Comment by EnixCoda** [comment]
`v3.7.2` has been uploaded. It adds a new setting for falling back PJAX mode in case the issue happen again.

https://github.com/EnixCoda/Gitako/wiki/Pjax-Mode

**Comment by chawyehsu** [comment]
The one on Microsoft Edge Addons Store is still 3.7.0, is it pending review?

**Comment by EnixCoda** [comment]
@chawyehsu  Yes, it takes 2 weeks on avg. for Edge Store to review addons, way slower than the other 2 stores. And 3.7.1 was skipped for Edge, now 3.7.2 is under review.

I'd suggest you install Gitako from Chrome Store even if you are using Edge.

**Comment by EnixCoda** [comment]
Reopening now as GitHub has rolled out the new redirection strategy again. Gitako would disappear after redirecting. Luckily, disabling `Native PJAX mode` can partially fix that. Gitako may still disappear after redirecting.

Also a new issue of navigation-back has arisen, which may have also existed a long time ago, #240

**Comment by EnixCoda** [comment]
Temporarily unpublished from Chrome Web Store.

**Comment by EnixCoda** [comment]
Got it fixed. :) Will release it soon if no other issue is found.

https://user-images.githubusercontent.com/7480839/176128818-a3c95c75-bd4e-468c-8fef-ee631fab6d45.mov

**Comment by EnixCoda** [comment]
`v3.7.3` has released, containing the fix to this issue.

Now available on Firefox, and will be available on Chrome after few hours.

**Comment by EnixCoda** [comment]
Now, in Chrome, clicking on tabs like `Issue` and `Pull Request` results in a full page reload rather than PJAX/turbo seamless redirect, even if Gitako is turned off. But it works well in Edge.

---

Well, turbo works in Chrome incognito window, perhaps some other extension is taking effect or my account is within some A/B test scope, nvm.
