### ISSUE TITLE
Why can't I find Gitako in Google Extension Store?

### ISSUE THREAD

**Issue by sinkinben** [EnixCoda/Gitako#241]
https://chrome.google.com/webstore/detail/gitako/giljefjcheohhamkjphiebfjnlphnokk

This link responses 404 at this moment.

**Comment by EnixCoda** [comment]
There is a serious issue that breaks Gitako's main features. #239 

And I have received negative comments from new users due to that. So Gitako was temporarily unpublished. I'll republish it once the issue is fixed.

**Comment by EnixCoda** [comment]
Let's keep this open until the new version is shipped ;)
