### ISSUE TITLE
Gitako isn't activated when opening a repo from the outside

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#250]
Example: open https://github.com/EnixCoda?tab=repositories&type=source, then click some repo, notice Gitako is missing until you refresh the page.

Previously, when you do this GitHub won't do PJAX, just normal navigation.

https://user-images.githubusercontent.com/44045911/178099018-0ccf20bf-1d66-45d9-8b11-3116889a98a1.mov

Respectively, Gitako can incorrectly appear outside a repo now:

https://user-images.githubusercontent.com/44045911/178099232-13c3cd1d-3349-4b5a-bb47-99c8a37e87c0.mov

**Comment by EnixCoda** [comment]
Thanks for logging the issue, it has been fixed in f6675e8163b20152d1d850e5a3eebae618b70c72

**Comment by EnixCoda** [comment]
Fixed in `v3.8.1`
