### ISSUE TITLE
Chrome extension doesn't working with github enterprise & manually token

### ISSUE THREAD

**Issue by hqsz** [EnixCoda/Gitako#253]
Hello, first thank you for making good product :)

I'm using gitako chrome extension(version 3.8.1) with github enterprise & manually token.
But after today morning my github enterprise repository was access denied 😢 

> Access Denied
Gitako needs access token to read this project. Please setup access token in the settings panel below.

I try to find some log about gitako, but failed.
can you help about this issue? thank u :)

**Comment by hqsz** [comment]
I tried same method at version 3.7.4, it was working well

**Comment by EnixCoda** [comment]
Thank you for reporting this! @lntuition 

I have confirmed the issue and will fix it ASAP!

**Comment by EnixCoda** [comment]
`v3.8.2` has been published to fix the issue. Please give another try, thanks!

---

Note: you can enable developer mode in extensions page to get the manual update button.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/7480839/179459969-c15bf605-956b-4aa1-9143-0acb93fe277b.png">

**Comment by hqsz** [comment]
Oh, thanks for fast fixing! With 3.8.2 it works well :)

**Comment by hqsz** [comment]
I will close this issue! thank you @EnixCoda
