### ISSUE TITLE
Long repo name may overflow in hidden sidebar

### ISSUE THREAD

**Issue by kidonng** [EnixCoda/Gitako#257]
If the repository name is very long and does not wrap, it may overflow in the hidden sidebar:

Example: https://github.com/wangtao03/Taiko_no_tatsujin_dokodon_Mystery_Adventure_Chinese_Patch

<img width="914" alt="image" src="https://user-images.githubusercontent.com/44045911/180864863-e590e913-d70f-406b-a288-3b460599a87d.png">

**Comment by kidonng** [comment]
Also happens here: https://github.com//refined-github/refined-github/pull/5791

<img width="832" alt="image" src="https://user-images.githubusercontent.com/44045911/181163519-ae09846f-18d5-4258-94e9-ef80da9207fe.png">

<img width="304" alt="image" src="https://user-images.githubusercontent.com/44045911/181163576-08e8e5e3-ea3f-4562-b3f4-4a3cbd53bf02.png">

Unrelated, but I really don't think you should use **branch name** style for **pull request title**. Either give it proper title style, or put branch name there (which is consistent with repository browsing).

**Comment by EnixCoda** [comment]
> Unrelated, but I really don't think you should use branch name style for pull request title. Either give it proper title style, or put branch name there (which is consistent with repository browsing).

Thanks, I'll consider about it.

**Comment by EnixCoda** [comment]
Fixed in `v3.8.3`

The style for PR titles may be updated in future.
