### ISSUE TITLE
Handle double (or even more) slashes in URL

### ISSUE THREAD

**Issue by EnixCoda** [EnixCoda/Gitako#258]
Such URL can take users to the desired page but Gitako cannot resolve the tree properly, because the URL contains double slashes `//` after `github.com`.

https://github.com//EnixCoda/Gitako/pull/247

**Comment by kidonng** [comment]
FYI, this is what we use in Refined GitHub: https://github.com/refined-github/github-url-detection/blob/1663cd904c179a5fbd95c008d3a54f400a02162c/index.ts#L686-L687

**Comment by EnixCoda** [comment]
> FYI, this is what we use in Refined GitHub: https://github.com/refined-github/github-url-detection/blob/1663cd904c179a5fbd95c008d3a54f400a02162c/index.ts#L686-L687

@kidonng Thanks, I have read some source code last time you shared it with me.

**Comment by kidonng** [comment]
Reiterating what I said in #243: this issue is different and simpler, we just drop duplicates.

**Comment by EnixCoda** [comment]
Fixed in `v3.8.3`
