### ISSUE TITLE
[Gitee] header of gitako seem to be covered by gitee's default header.

### ISSUE THREAD

**Issue by yzqdev** [EnixCoda/Gitako#264]
Now it's hard to collapse or open the sidebar, the picture is as follows.

![image](https://user-images.githubusercontent.com/20037151/190956571-404ee56a-6ab7-4a67-ac69-2e49a37012b4.png)

### maybe the reason is that gitee's header has a selector `#git-header-nav` which set z-index to 1002

![image](https://user-images.githubusercontent.com/20037151/190957334-a642b35e-8ab9-45cb-8f64-9aec31142c6f.png)

**Comment by EnixCoda** [comment]
fixed by 3f7463d5b7f0271f583c79e1eab17c3d35af4ad8
