### ISSUE TITLE
Could not refresh the whole paeg when click the filename?

### ISSUE THREAD

**Issue by fedono** [EnixCoda/Gitako#265]
Hi, I really like this chrome plugin, and it helps me a lot when I view any repo.

There is one question I was wondering, when I expanded then whole repo filelist, and click any filename, file content has fetched and render in the view zone, and then the whole page refreshed, I just wondering why the whole page refreshed, is there any setting that I can close, I just not found it.

**Comment by EnixCoda** [comment]
Hi @fedono 

Thank you for your appreciation and feedback! 😁

However, I cannot reproduce it on my end. I am using `Gitako v3.9.0` on `Chrome v106` & `Chrome v108`, `Edge v106`, for macOS.

Please try the methods below then give another try.
- upgrade your browser and browser extensions
- disable other extensions to make sure no extension is in conflict with Gitako

And let me know if the issue still exist. If so, a reproduction video/GIF would be very great!

Thank you very much!

**Comment by fedono** [comment]
@EnixCoda Thanks for responding, use the method you suggested I found the cause.

when I disable the [circle-reader](https://chrome.google.com/webstore/detail/circle-reader/dhpfcgilccfkodnhbllpiaabofjbjcbg) extension, the problem sovled.

Thanks, Have a good day! 😁
