### ISSUE TITLE
Blink tremor when the window is small

### ISSUE THREAD

**Issue by schmurtzm** [EnixCoda/Gitako#269]
Hi, when the left menu is collapsed, reducing the window size triggers a kind of tremor of the the left menu.

![firefox_T7MD75ZYT0](https://user-images.githubusercontent.com/7110113/204014721-ee1965e6-73f2-4a48-b4c8-29177461efbe.gif)

**Comment by EnixCoda** [comment]
Thank you! 

Also reproduced on Chrome.
