### ISSUE TITLE
Sidebar would reset after navigation

### ISSUE THREAD

**Issue by Jericho** [EnixCoda/Gitako#279]
I am using Gitako v3.10.2 and I have it configured to "persistent" dock mode as you can see in this screenshot:
![image](https://user-images.githubusercontent.com/112710/215336133-705581d6-4b51-4baa-ad1b-91dac74ad3d5.png)

My expectation is that Gitako will remain open as I browse files in a GitHub repo. However, that's not what I am experiencing. What I observe is that the panel collapses whenever I click on a file. This short video demonstrates what I'm experiencing:

https://user-images.githubusercontent.com/112710/215336399-b212c5a4-2ab4-4d89-8f3e-afd02f60ef0b.mp4

**Comment by EnixCoda** [comment]
Hi @Jericho  Thank you for reporting this issue.

However, I cannot reproduce it on my side. I tried the same operations as you have demonstrated, on Edge + macOS.

Would you please disable other browser extensions to see if any of them are in conflict with Gitako? Thanks!

**Comment by Jericho** [comment]
As you requested, I disabled all other extensions but the problem persists
![image](https://user-images.githubusercontent.com/112710/215381524-64dc69b7-467b-4079-bbdf-fb870609990b.png)

**Comment by Jericho** [comment]
I don't know if this is important, but I see an exception when I display the DevTools:
![image](https://user-images.githubusercontent.com/112710/215381884-76f60aeb-aa07-44ed-80e1-e009b9793772.png)

**Comment by EnixCoda** [comment]
It is fine. The exception is not thrown from Gitako.

This time I tried to reproduce it on a Windows PC but still no luck. It only has Gitako in the Edge extension list, too. As close to your environment as possible.

If you don't mind, would you give another try on other browsers, like Chrome? I'll really appreciate it!

**Comment by Jericho** [comment]
I installed Chrome and Gitako. It works as expected:

https://user-images.githubusercontent.com/112710/215501562-6ba726a1-dfa6-4dcc-943c-61e4dd3f0b75.mp4

**Comment by EnixCoda** [comment]
Let's keep this issue open to see if other users also encounter this.

**Comment by sixgodfan** [comment]
I also have this problem.
Click the version number in the lower right corner to return to normal

**Comment by 1chz** [comment]
I am experiencing the same issue.
here is my environment:

PC: M2 Pro
OS: Ventura 13.3.1(22E261)
Chrome: 112.0.5615.121
Gitako: 3.10.3

I would appreciate it if this information helps to resolve the issue.

**Comment by EnixCoda** [comment]
Very interesting that this issue happens on both macOS and Windows, both Chrome and Edge. 🤔

**Comment by EnixCoda** [comment]
Hi @Jericho @shirohoo 

Would you please record a longer video that including such steps:
1. Pin sidebar and expand it
2. Click on a file to navigate
3. Wait for navigation to finish
4. Click on the Gitako sidebar icon to expand it

The original video posted by @Jericho is quite good that it has step 1-3 included.
By doing the extra step 4, perhaps I can get more clue about what is going on.
Thank you very much!

**Comment by Jericho** [comment]
Here's a slightly longer video that demonstrate Gitako collapsing every time I click on a file in a repo:

https://user-images.githubusercontent.com/112710/233104614-93e78a0e-97e0-4881-93fe-a6ee9d0e8d84.mp4

**Comment by EnixCoda** [comment]
@Jericho  Thank you for the fast respond!

1. Pin sidebar and expand it
2. **Type anything into the search input**
3. Click on a file in the search result to navigate
4. Wait for navigation to finish
5. Click on the Gitako sidebar icon to expand it

Would you please give another try with one more step?
I'd like to confirm if Gitako has been reset after navigating.

**Comment by Jericho** [comment]
https://user-images.githubusercontent.com/112710/233198123-a8d217ae-e2a1-41aa-b4d6-7897d2d4a2f7.mp4

**Comment by EnixCoda** [comment]
Thanks! I can confirm that sidebar reset after navigation.

**Comment by magicdawn** [comment]
I think this is related to new GitHub "code view" feature.

**Comment by EnixCoda** [comment]
Feel free to reopen if anyone still encounter this after `v3.11.3`
