### ISSUE TITLE
Authorization Fails If using GLOC

### ISSUE THREAD

**Issue by semi710** [EnixCoda/Gitako#284]
Authorization Fails if using [GLOC](https://github.com/kas-elvirov/gloc) extension
Browser Firefox

**Comment by EnixCoda** [comment]
Thanks for reporting this issue.

It seems GLOC is modifying elements originally rendered by Gitako. Which only take effect when you have token set, via OAuth or manually.

I'm afraid it is beyond Gitako's ability to adapt the elements modified by other extensions. Sorry!
