### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by sixgodfan** [EnixCoda/Gitako#287]
Only able to search files, hope to support regular search code content, thank you

**Comment by EnixCoda** [comment]
I'm afraid that is beyond Gitako's designed purpose and I'd suggest you try [githubdev](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor)

**Comment by andry81** [comment]
@sixgodfan These browser extensions a bit more powerful: https://github.com/andry81-devops/external-resources#text-edit
