### ISSUE TITLE
Browsed rewrited repository does not affect Gitako directory tree

### ISSUE THREAD

**Issue by andry81** [EnixCoda/Gitako#288]
If try to rewrite an opened in a browser repository and click on the repository link both in the Gitako side panel or in the GitHub page, then the directory tree won't be properly updated. It would still show deleted directories and files. Only the page reload affects the directory tree.

**Comment by EnixCoda** [comment]
Hi @andry81 

Could you please provide a video demonstrate the steps to reproduce the issue? I'll really appreciate it, Thank you!

**Comment by andry81** [comment]
@EnixCoda Just use [git-filter-repo](https://github.com/newren/git-filter-repo) to rewrite a repository.

Steps:

1.  Create repository with 3 commits adding in each 3 files: `file1.txt`, `files2.txt`, `file3.txt`.
2.  Open a browser with the repository and pin the side panel.
3.  Run `git-filter-repo --invert-paths --path 'file2.txt'` in the working copy.
4. Force push the working copy.
5.  Click on `user/repo` link on the GitHub page of the repository.
6.  Observe `file2.txt` in the side panel.

**Comment by EnixCoda** [comment]
Is that similar to the situation that pushing a commit then click on `user/repo` link, right?

If so, that is an won't fix case for Gitako. As it is not expected to detect repo update that timely.

**Comment by andry81** [comment]
> Is that similar to the situation that pushing a commit then click on `user/repo` link, right?

Can not say, I didn't test that. I've tested particularly the last (3d) commit and the file tree must affect the tree related to the last opened commit (3d). If you try to add 4th commit, then it would be a different situation.

In any case the tree rewrite is not equivalent to push a new commit, because of hash changes in all commits on the way of a rewrite.

**Comment by EnixCoda** [comment]
Not sure if I fully understand the issue this time.

You are navigating after making changes to the branch, right? Gitako does not support actively update to the latest state, it only fetch the file tree on repo change, branch(commit) change.

Thank you for understanding!
