### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Properrr** [EnixCoda/Gitako#29]
Is it possible to add different themes or just dark theme?

**Comment by EnixCoda** [comment]
Hi @Properrr , that's a good idea!

I'll give a try on it.

**Comment by EnixCoda** [comment]
For people looking for dark mode support，I'd suggest use [Dark reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) or [Stylus](https://github.com/StylishThemes/GitHub-Dark). They furnish GitHub into dark mode as well as Gitako.
