### ISSUE TITLE
Support Global navigation update

### ISSUE THREAD

**Issue by jerryc127** [EnixCoda/Gitako#290]
Github is testing new  Global navigation
![image](https://user-images.githubusercontent.com/16351105/234018705-c2b1a78c-87e9-44c8-8068-3114cee31287.png)

when enable it, the gitako not working

**Comment by EnixCoda** [comment]
Thanks for letting me know! Update coming soon in `v3.11.0`

**Comment by jerryc127** [comment]
edge插件商场 没更新？

**Comment by EnixCoda** [comment]
@jerryc127 The Edge add-on store always take longer time to review updates than the other browsers. You may install from Chrome Web Store for Edge. Thanks!

**Comment by jerryc127** [comment]
> Thanks for letting me know! Update coming soon in `v3.11.0`

有点问题
有些界面没有显示 Gitako
例如 https://github.com/ArtalkJS/Artalk/

**Comment by EnixCoda** [comment]
> > Thanks for letting me know! Update coming soon in `v3.11.0`
> 
> 有点问题 有些界面没有显示 Gitako 例如 https://github.com/ArtalkJS/Artalk/

感谢！

---

Previous fix could not resolve repositories under organizations. Will be fixed in `v3.11.2`
