### ISSUE TITLE
Avoid translating file and folder names when using Chrome's built-in translation tool

### ISSUE THREAD

**Issue by jinliming2** [EnixCoda/Gitako#291]
Currently, the file and folder names are translated, when using Chrome's built-in translation tool to translate whole pages. This is annoying because the translation is not perfect, and because Gitako is using the virtual list render in FileExplorer, translation may not work when the list scrolling unless the page is scrolled.

To avoid this, may add the `translate="no"` property to the HTML `div` node to disable the translation.
![image](https://user-images.githubusercontent.com/10294977/235346055-5f344c4b-9267-4cf7-a798-b182107cfd43.png)

**Comment by EnixCoda** [comment]
Thanks for bringing this up. It would make perfect sense if GitHub's file list also do this to prevent being translated. Otherwise, Gitako would better follow GitHub's behavior.
