### ISSUE TITLE
GitHub page crashes when triggering code menu context

### ISSUE THREAD

**Issue by EnixCoda** [EnixCoda/Gitako#294]
If click on the `...` button next to line number, page content will become `Looks like something went wrong!`

<img width="395" alt="image" src="https://github.com/EnixCoda/Gitako/assets/7480839/4336151d-cb79-47bb-8e4e-27ea6290d593">

<img width="426" alt="image" src="https://github.com/EnixCoda/Gitako/assets/7480839/3deea4c2-f323-4b6e-b632-d605877447d0">

This defect is because `anchored-position.js` cannot handle elements that is not under `body`.

<img width="610" alt="image" src="https://github.com/EnixCoda/Gitako/assets/7480839/89ba27f0-4ab5-4361-b233-049fa708cccd">

Gitako is mounted out of `body` to fix other issue.

~I remember that I've reported this issue to the maintainer of `@primer`, where `anchored-position.js` come from, but they did not have plan to fix it.~ Or maybe I didn't, my memory lied. I did not found my comment in their issues.

So this issue won't be fixed.

**Comment by EnixCoda** [comment]
This defect is quite severe, I'll not be surprised if many users uninstall Gitako.

**Comment by snowe2010** [comment]
This looks like the same problem as using `T` to jump to search and as soon as you type something it crashes the whole page with the same error message. Sadly this is a huge blocker for me and I will need to disable gitako until(if) it's fixed.

**Comment by EnixCoda** [comment]
A good news. This issue seems possible to be fixed because the other issue of `Gitako is mounted out of body to fix other issue` seems not an issue anymore.

**Comment by EnixCoda** [comment]
Alright, the other issue still exist. :|

~Gitako might disappear after clicking navigation links in GitHub content. And even leaving a blank area if you have pinned its sidebar.~ Fixed in 3.11.6
