### ISSUE TITLE
[Nonissue] Thank you for your contribution

### ISSUE THREAD

**Issue by iwishwp** [EnixCoda/Gitako#296]
Thank you

**Comment by imxieke** [comment]
thank you 😄

**Comment by CodeLikeAGirl29** [comment]
thanks so much!! i loved using Gitako!

**Comment by AriaLyy** [comment]
Thank you

**Comment by ShiftWatchOut** [comment]
Thank you.

**Comment by ghaschel** [comment]
[F] - Thank you so much for your work.. Gitako really did improve a LOT using Github.

**Comment by knight02-bit** [comment]
Thank you!

**Comment by yilmazdurmaz** [comment]
Thanks a lot!

**Comment by WindowsXp-Beta** [comment]
Thanks for so much for your work.

**Comment by anandncode** [comment]
Thank you so much for all the features that gitako offered. It's a wonderful plugin for github

**Comment by fatgy** [comment]
Thank you so much. :smiling_face_with_three_hearts:

**Comment by junu-kk** [comment]
Thank you

**Comment by ansible-starlight-space** [comment]
Thank you! Gitako has made my life so much easier, and I wish you many happy ahead.

**Comment by 0xlength** [comment]
Thank you so much！！！
