### ISSUE TITLE
可否支持导出文件列表？

### ISSUE THREAD

**Issue by StrollStars** [EnixCoda/Gitako#305]
如题，网页版默认显示上限1000项，而且好像也不支持下一页，所以直接通过网页界面导出文件列表最多只有1000项。
希望能够支持导出文件列表，突破1000的上限。

**Comment by EnixCoda** [comment]
Hi 请问是说 GitHub 内置的文件浏览只支持 1000 项吗？
对于你的需求，可以提供更完整的使用场景吗？
目前看来不太确定导出文件列表应该是 Gitako 具备的功能……

**Comment by StrollStars** [comment]
@EnixCoda 确实比较小众，我的想法是不把仓库下载到本地，而只保留一份文件清单，有文件名、大小和时间等信息，需要的时候查找文件列表，再去下载。

**Comment by EnixCoda** [comment]
@StrollStars 也许是 GitHub 自己的搜索框已经具备的功能了，配合一些 filter 可以做到特定 repo 下的搜索等效果，而且搜索结果时效性高
