### ISSUE TITLE
一些功能请求

### ISSUE THREAD

**Issue by AriaLyy** [EnixCoda/Gitako#31]
很好到插件，比octotree良心多了。
作者可以将插件上传到火狐吗？
作者能否适配下码云？

**Comment by EnixCoda** [comment]
你好，非常高兴 Gitako 能受到你的喜爱！

目前 Gitako for Github 已经日趋稳定，我会更多浏览器、更多平台的适配计划的。

谢谢！

**Comment by AriaLyy** [comment]
👍

**Comment by EnixCoda** [comment]
你好，Gitako 现已支持 Firefox。

欢迎试用！
