### ISSUE TITLE
[feature request] 添加默认收起 Gitako 的选项

### ISSUE THREAD

**Issue by batkiz** [EnixCoda/Gitako#33]
进入网页后不默认展开侧栏的 Gitako，而是在有需要时可将其 pin 起来（参考 octotree）

**Comment by EnixCoda** [comment]
你好，感谢你的建议，我会考虑加入相关设置项。

此外，现在 Gitako 会根据当前页面判断是否应当显示，请问你最不希望在哪些页面看到 Gitako 被自动展开呢？谢谢！

**Comment by batkiz** [comment]
我的需求比较奇怪，因为我在哪都不想看到它自动展开 😅

**Comment by EnixCoda** [comment]
已添加 `Intelligent Toggle` 设置项，默认开启
关闭后将记录用户手动开启/关闭侧边栏的状态
