### ISSUE TITLE
Regex filter doesn't work as expected

### ISSUE THREAD

**Issue by yangshuairocks** [EnixCoda/Gitako#35]
I wanted to use the filter only to show all `.go` files. However, a lot of files that do not end with `.go` were displayed. See the below image. Is this a bug, or where am I wrong?
![image](https://user-images.githubusercontent.com/39968/66373419-32266f00-e9db-11e9-8879-5f83f1aa0043.png)

**Comment by EnixCoda** [comment]
hi @yangshuairocks , thanks for your feedback!

This behavior is actually a feature. As Gitako will list items that match either `\.go$` (exactly what you typed) and `g.*?o` (any string which includes `g` in front of `o`).
And the results of `\.go$` will be listed in front of others, as you can see, `main.go` is listed as the first item. For the rest, their names include both `g` and `o`.

Sorry for this misleading behavior as I did not have time to implement the feature which highlights matched chars in file name (in your case, `.go` should be highlighted in other color).

I am considering such a temporary compromise solution: adding a button to toggle search mode between vanilla regex mode and currently implemented *intelligent* mode. How's that sound?

**Comment by yangshuairocks** [comment]
That would be great. But I suggest making the vanilla regex mode as the default mode. Because that's what the search box states what it will do (search files by regex).

**Comment by EnixCoda** [comment]
Rolled out `v0.5.11` with enhanced search input. Now users would to type regular expressions on their own.

> BTW, I removed the *intelligent* mode as I found out that it was not as useful as I expected.

**Comment by yangshuairocks** [comment]
Thank you so much! Gitako is more useful now.
