### ISSUE TITLE
在 Releases 页面也自动展开了，且提示 Access Denied

### ISSUE THREAD

**Issue by Jackeriss** [EnixCoda/Gitako#36]
在 Github repo 的 Releases 页面如：https://github.com/EnixCoda/Gitako/releases
时不应该自动展开。
展开还无法展示目录树，提示 Access Denied。
能否和 [Pull requests 页面](https://github.com/EnixCoda/Gitako/pulls) 的行为一致呢？

**Comment by EnixCoda** [comment]
你好，感谢你的反馈！

我使用最新版(v0.5.11)未能复现你说的问题。不管是通过重定向进入还是直接加载 release 页面，Gitako 都会自动收起。自动展开的功能应该是正常运作的。

我想你遇到的问题可能是——

1. Gitako 未被赋予当前所访问的项目的权限，于是它通过强制展开的方式及时告知用户
    > 不属于你的个人账户的私有仓库需要在 OAuth 时额外批准权限，或通过手动创建 Access token 获得全部权限 [Wiki](https://github.com/EnixCoda/Gitako/wiki/How-to-create-access-token-for-Gitako%3F)
2. 网络请求发生偶发错误，导致它误以为遇到了 1 的问题
3. 设置中的 `Intelligent Toggle` 选项被关闭了，使得 Gitako 的开启状态被无视页面内容地保留

希望以上解决了你的困惑，
如还有问题，请提供更具体的信息供我进一步确认。

谢谢！

**Comment by Jackeriss** [comment]
![image](https://user-images.githubusercontent.com/7183428/66990406-b4f4ab80-f0f8-11e9-9ed6-da42205819e6.png)
1 和 3 应该可以排除了，如果是 2 为什么我多次尝试只有 release 页面有这个问题呢

**Comment by EnixCoda** [comment]
`多次尝试只有 release 页面有这个问题`——意思是其他仓库的 release 页面无此问题？那真是非常的神奇。

请问截图是在什么 URL 下截的呢？我尝试了一番，没有找到能够显示 `Find Tag` 的 URL 。

**Comment by Jackeriss** [comment]
所有仓库的 release 页面都有这个问题。
完整的截图：
![image](https://user-images.githubusercontent.com/7183428/66996088-a57a6000-f102-11e9-89a5-08e5e2e0ccb4.png)

**Comment by EnixCoda** [comment]
感谢，这些信息非常关键！

我大致知道出问题的地方了，会尽快检查并修复。

**Comment by EnixCoda** [comment]
你好，已上传了针对此问题的修复版本，其中增加了更严格的分支检测机制。

如问题仍然存在，还请 reopen issue 。
