### ISSUE TITLE
Support Gitee(码云)

### ISSUE THREAD

**Issue by EnixCoda** [EnixCoda/Gitako#38]
Gitee has become more popular than ever. It is time to support it.

[API ref](https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoStargazers?ex=no)

**Comment by EnixCoda** [comment]
This partially resolves #31

**Comment by EnixCoda** [comment]
This is blocked by #26 as Gitako relies on styles inherited from GitHub webpage.

Gitee doesn't provide those styles. If we migrate now, styles could mess up.

**Comment by yidasanqian** [comment]
gitee 可以不使用依赖于github webpage的styles吗

**Comment by EnixCoda** [comment]
@yidasanqian 那需要 Gitako 通过内置完整的样式方案来实现跨网站的稳定UI。如果内置的是目前的 GitHub 的主题（Prime），我认为也不太贴合 Gitee 的风格。

有什么建议吗？

**Comment by yidasanqian** [comment]
参考下这个https://gitee.com/inu1255/GitCodeTree，我对前端不太熟，你看下统一风格有困难就不统一，github和gitee分开也行

**Comment by EnixCoda** [comment]
这似乎是 fork 了 Octotree 并改了数据请求模块的项目

Octotree 的 UI 基本上也是基于 Prime ，我考虑下改进 Gitako 的 UI ，尽量能够贴合多个站点吧

**Comment by EnixCoda** [comment]
Done with 1f92181337b219244edacd56a8421234ad0ebbd4

Coming soon
