### ISSUE TITLE
文件目录过多时无法滚动浏览

### ISSUE THREAD

**Issue by liuancheng** [EnixCoda/Gitako#39]
访问以下地址，展开pages/example 文件夹，出现无法滚动的情况
https://github.com/youzan/vant-weapp/tree/dev/example/pages
![image](https://user-images.githubusercontent.com/13687263/67744022-6087ef00-fa5b-11e9-93f3-3b4d0c842052.png)

**Comment by EnixCoda** [comment]
你好，感谢你的反馈！

我使用最新版 Chrome 浏览器进行的测试，没有遇到你所说的问题。

请尝试升级 Chrome 后重试（之前偶有几个版本的Chrome也出现过类似的问题）。

如果问题仍然存在，还请提供你的操作系统、浏览器版本、Gitako 版本等信息。

谢谢🙏

**Comment by EnixCoda** [comment]
我又仔细看了一下截图，从 UI 可以识别出你使用的仍是较旧版本的 Gitako （调整尺寸的 dragger 在文件列表的左侧）。

我相信升级 Gitako 版本就能解决这个问题，并通过最新的 GItako 功能进一步提升 GitHub 体验！

Good lock！

**Comment by liuancheng** [comment]
谢谢您的反馈，我待会更新下chrome 及插件试一下，如果有问题在给你反馈，非常感谢您开源的插件。

祝您生活愉快，工作开心🥳

From Ancheng

在 2019年10月29日，17:57，Enix <notifications@github.com> 写道：

﻿

你好，感谢你的反馈！

我使用最新版 Chrome 浏览器进行的测试，没有遇到你所说的问题。

请尝试升级 Chrome 后重试（之前偶有几个版本的Chrome也出现过类似的问题）。

如果问题仍然存在，还请提供你的操作系统、浏览器版本、Gitako 版本等信息。

谢谢🙏
