### ISSUE TITLE
某些github仓库打开失败

### ISSUE THREAD

**Issue by AriaLyy** [EnixCoda/Gitako#40]
如：https://github.com/is/jsch

**Comment by EnixCoda** [comment]
你好，我尝试了一下可以打开——

![image](https://user-images.githubusercontent.com/7480839/67999206-3e2de580-fc96-11e9-84d2-4491052b4601.png)

麻烦确认一下是否是网络偶然不稳定造成的部分请求失败，
或提供网页控制台的错误信息帮助我进一步定位问题，
谢谢！

**Comment by AriaLyy** [comment]
好像是网络的问题，一旦网络波动，猪头就变红了。出现了几个404，现在没有了。。。
![image](https://user-images.githubusercontent.com/10437293/67999881-efce1600-fc98-11e9-94a7-1b14ab8ecda7.png)

**Comment by EnixCoda** [comment]
😂 其实不是“猪头”—— https://octicons.github.com/icon/octoface/
