### ISSUE TITLE
Add some icons

### ISSUE THREAD

**Issue by BrunoFL** [EnixCoda/Gitako#42]
Icons, colors :smile: 

Add icons for file type.

**Comment by EnixCoda** [comment]
Hi @BrunoFL 
Thank you for giving a feedback

Gitako is using icons from https://octicons.github.com/ to keep it looks as native to GitHub as possible. But I have to admit that having more rich and accurate icons will definitely help recognize files.

I'll find out if it is possible to integrate another icon lib into Gitako.

**Comment by EnixCoda** [comment]
And size might be another issue we should take into consideration.

Making use of an icon lib may significantly increase the size of Gitako. 🤔

**Comment by BrunoFL** [comment]
Size is really important?
In addition, some icons in svg should have a slight impact ?


I'm sure you'll do it for the better :smile:

**Comment by rinormaloku** [comment]
@EnixCoda 

Icons would make sense, I switched to gitako due to the amazing search bar, but whenever navigating through the files using the filetree it is not as intuitive as for e.g. octotree.

I expect the icons will be installed with the extension and a bigger size that is just a one time download wouldn't make a huge difference.

If you are in for the icons, I will asap I get some free time work and integrate this.

**Comment by EnixCoda** [comment]
@rinormaloku 
Thank you for the generosity of your time and appreciating Gitako. I have a plan for the icons now, stay tuned ;)

![image](https://user-images.githubusercontent.com/7480839/69901512-ab2fba80-13bd-11ea-8c98-0f8db375b6e1.png)

**Comment by BrunoFL** [comment]
really cool !

**Comment by EnixCoda** [comment]
Done with 02b33776b7eda46fef4acbb2ab2c105bf7f7e4a9

**Comment by doongjohn** [comment]
what do you think about adding material-icons using this: https://github.com/PKief/vscode-material-icon-theme/tree/master/icons

**Comment by EnixCoda** [comment]
@doongjohn 
Material icons is a very elegant icon set, I personally like it much too! But it is not as rich as the `vscode icons`, nor does it fit GitHub well as Octoicons do. So it might not be added before more voices arise.
