### ISSUE TITLE
support Safari

### ISSUE THREAD

**Issue by EnixCoda** [EnixCoda/Gitako#43]
Gitako for Safari is available via TestFlight.

https://testflight.apple.com/join/1hefQt6Y

---

![image](https://user-images.githubusercontent.com/7480839/72684788-94385980-3b1e-11ea-862f-2705c295dc23.png)

Did some research on migrating to Safari, it is not as hard as I thought. But there are still few edge cases need to be take care of.

**Comment by EnixCoda** [comment]
There is `safari.extension` in safari, may polyfill `browser` with it.

**Comment by wangfenjin** [comment]
@EnixCoda ETA for release? Need it!

**Comment by EnixCoda** [comment]
Glad to see that Apple has made developing extensions for Safari easier by releasing the [Safari Web Extension](https://developer.apple.com/videos/play/wwdc2020/10665/).

**Comment by yulinfeng000** [comment]
hope published soon, even beta

**Comment by EnixCoda** [comment]
Having trouble enrolling Apple Developer Program for unclear reasons, the enrolling page does not explain clearly. :(

Will contact Apple's support about this.

**Comment by EnixCoda** [comment]
2 months past and no good news from Apple. :(

And it seems that Safari does not allow install extensions from files in general.

**Comment by slaysd** [comment]
Has any update about support Safari Web Extension?

**Comment by EnixCoda** [comment]
@slaysd  Unfortunately, still no update from Apple yet 😐

I will try to register another account later

**Comment by EnixCoda** [comment]
Good news! I checked Apple Developer Program moment ago and found out that I am now successfully enrolled!

Will try to release the Safari version soon!

I hope I could get notified in time when Apple addressed my ticket, but they didn't.

**Comment by zhongjiajie** [comment]
Looking forward to the safari extension

**Comment by EnixCoda** [comment]
Struggled with App Store distribution a few times and had no luck. I'd temporarily release using [GitHub releases page](https://github.com/EnixCoda/Gitako/releases). You can have a try although it is not fully ready.

### A brief setup tutorial
1. Download and unzip the file
2. Move the `Gitako.app` into your `Applications` folder
    During my test, Gitako did not work in Safari if this step is skipped.
3. Launch it (you might need to permit it from System Preferences -> Security -> General)
4. In Safari Preferences -> Advanced, check `Show Develop menu in menu bar`
5. With Safari focused, on menu bar -> Develop -> Allow unsigned extensions [1]
    _I got stuck when signing the app and distributing it to Mac App Store. That step will not be required when I figure out how to solve that._
    <img width="423" alt="image" src="https://user-images.githubusercontent.com/7480839/177678194-53bc85dd-c29c-4a08-87d4-69f9f270350e.png">
6. In Safari Preferences -> Extensions, enable Gitako.
    <img width="904" alt="image" src="https://user-images.githubusercontent.com/7480839/159165831-5a8abb5f-d0c0-4728-9fa0-4587cafb7fb8.png">
7. Visit github.com and enable Gitako from nav bar (I'd recommend check the last option if you may need Gitako on other platforms _in future_. For now, Gitako may not work on other sites.)
    <img width="1392" alt="image" src="https://user-images.githubusercontent.com/7480839/159165888-57d33aaf-5189-41c0-992d-4a9426e306ce.png">

---

Note:
1. Gitako for safari may not support platforms other than github.com, even GitHub Enterprise. That may get fixed when updating Gitako's manifest to v3 this year.
2. Multiple instances of Gitako may show up at the same time. Not sure why & how to fix that.

**Comment by aurexav** [comment]
Great job. But it looks like the dark mode was missing.

**Comment by EnixCoda** [comment]
@AurevoirXavier Thanks for reporting the issue. But I cannot reproduce it locally. We'll have next release for Safari soon, please stay tuned and try again then.

**Comment by aurexav** [comment]
> @AurevoirXavier Thanks for reporting the issue. But I cannot reproduce it locally. We'll have next release for Safari soon, please stay tuned and try again then.

Is that ready now?

**Comment by EnixCoda** [comment]
@AurevoirXavier I was to release that but got occupied by issues cause by GitHub updating its redirecting lib, from PJAX to turbo. #239 #240 #241 #243 

A temporary release for Safari should be available in few days. Thank you for your patience.

**Comment by EnixCoda** [comment]
Gitako v3.7.4 for Safari is available now! You can get it from [the release page](https://github.com/EnixCoda/Gitako/releases/tag/v3.7.4).

And I've updated the installation instructions [above](https://github.com/EnixCoda/Gitako/issues/43#issuecomment-1073255647). Please install according to that.

**Comment by EnixCoda** [comment]
> If I pin the plugin, it will push the GitHub contents to the right side. Can I have a float-style pin?

@AurevoirXavier That was once supported but has been removed from Gitako. Maintaining a hack of GitHub content has been proved to be a costly work. Sorry.

**Comment by aurexav** [comment]
> @AurevoirXavier That was once supported but has been removed from Gitako. Maintaining a hack of GitHub content has been proved to be a costly work. Sorry.

I've deleted that comment.
If people didn't use a wide screen, that would not be a problem, and it will shield the content at the same time.

**Comment by EnixCoda** [comment]
Now you can join Test Flight to get the latest Gitako for Safari! And it should be easier to update than manual install.

https://testflight.apple.com/join/1hefQt6Y

**Comment by popshia** [comment]
Hi, I would like to ask if there's any update supporting Safari?
Test Flight testing is down :(

**Comment by EnixCoda** [comment]
@popshia Thanks for reminding. I'll republish Gitako in a few days.

**Comment by popshia** [comment]
Thank you so much for keep supporting Safari!

**Comment by popshia** [comment]
@EnixCoda Thank you so much for keep supporting on Safari, much appreciated!

**Comment by EnixCoda** [comment]
@popshia Published! :D

**Comment by popshia** [comment]
@EnixCoda Thank you so much!

**Comment by EnixCoda** [comment]
No plan to release Gitako for Safari anymore. If you'd like to use Gitako on Safari, please build on your own following the [doc](https://github.com/EnixCoda/Gitako/blob/develop/contributing.md#safari-macos-only)

I'm still willing to address issues if anyone encounter during building it!
