### ISSUE TITLE
现在背景为啥默认是白色了？

### ISSUE THREAD

**Issue by AriaLyy** [EnixCoda/Gitako#46]
![image](https://user-images.githubusercontent.com/10437293/74119435-5b117780-4bfa-11ea-9039-3856a72f37c0.png)
昨天还是背景还是跟随网页的颜色的，今天怎么变成白色的了...

**Comment by EnixCoda** [comment]
请问你是通过 Stylus 开启 dark mode 的吗？
如果是的话，可能因为近日刚刚 [适配了 Stylus](https://github.com/StylishThemes/GitHub-Dark/issues/1055) ，而 Stylus 在适配方面出现了偏差？你可以在 Stylus 开启 issue

否则的话，烦请告诉我如何复现这一问题，多谢🙏

**Comment by AriaLyy** [comment]
我用的是 dark reader 并且开启了dark mode 模式

**Comment by EnixCoda** [comment]
OK，我知道原因了。

我考虑一下采取何种策略使得适应大多数情况。

<details>
<summary>原因</summary>
为了适配 Stylus ，生成了独立 css 文件，运行时经由浏览器处理插件样式文件的特殊方式注入样式，这样注入的样式不会在 document.head 中（以前通过 webpack style loader 处理的样式是会的），也就不能被其他自动化处理色彩的插件（包括 dark reader）二度处理。
</details>

**Comment by EnixCoda** [comment]
已找到两全的解决方案，近日会发布。

**Comment by AriaLyy** [comment]
👍
