### ISSUE TITLE
Gitako logo causes top bar elements shrink to center.

### ISSUE THREAD

**Issue by Elderry** [EnixCoda/Gitako#47]
With Gitako enabled:
![image](https://user-images.githubusercontent.com/1892221/74217754-4a88fc00-4ce3-11ea-8af9-3af70783116b.png)
Without Gitako:
![image](https://user-images.githubusercontent.com/1892221/74217780-612f5300-4ce3-11ea-975a-73d6980ec017.png)

**Comment by Elderry** [comment]
I can assume the logo needs some space, but I hope the elements in the right, such as avatar, don't move.

**Comment by EnixCoda** [comment]
Hello @Elderry 
Yes, this a fix for few style issue. Let me explain and see if we can accomplish a better solution.

## Scenes
1. if not shrink (header) when (Gitako is) collapsed
    ![not open, not shrank](https://user-images.githubusercontent.com/7480839/74225178-2504ee00-4cf5-11ea-9c0c-5a441e9c5761.png)
    Issue: Gitako icon overlays GitHub icon.

2. if not shrink when open
    ![open, not shrank](https://user-images.githubusercontent.com/7480839/74225279-5bdb0400-4cf5-11ea-816c-44a64364f8ae.png)
    Issue: Gitako sidebar takes more space of GitHub header when window is wider than 1280px. Search bar could be unusable. **I think this is not acceptable.**

3. if shrink when collapsed
    ![not open, shrink](https://user-images.githubusercontent.com/7480839/74225154-1cacb300-4cf5-11ea-8f02-64b58c26ae0b.png)

4. if shrink when open
    ![open, shrank](https://user-images.githubusercontent.com/7480839/74225163-20403a00-4cf5-11ea-817c-c7c2c96d8880.png)

---
I took 3 + 4 as the solution to prevent issues mentioned above.

Any suggestions?

**Comment by Elderry** [comment]
@EnixCoda First thanks for your attention, I can tell that you choose a practical solution amony available ones. I just want to point out this solution can be even better.

Here my question is that possible to just move the left part of top bar to right a little, without moving the right part? I'm not a front-ender so I'm afraid this is just a feature request, rather than professional suggestion.

**Comment by EnixCoda** [comment]
No worries, I'm open to any suggestions and discussion that could make Gitako better :)

> move the left part of top bar to right a little, without moving the right part

That is technically do-able, but hard.

Consider `moving the left part`, I think it should align with page content and looks like this.
![image](https://user-images.githubusercontent.com/7480839/74304726-d315a400-4d98-11ea-9491-47fc6c9ba97c.png)

Everything looks good. But when Gitako is open, it needs a complicated mechanism to achieve this as both width of window and sidebar is dynamic. Implementing that would take some time.

If anyone else also want this feature to be implemented, please leave a comment or simply thumb up to the original issue comment. I'll do when there are enough requests.

**Comment by Elderry** [comment]
You're right, it's resonable to shrink top bar content when the page content is centered. Only when the page content is full paged like when`split` option is checked in commit page, the shrink become wired.
![Annotation 2020-02-12 141426](https://user-images.githubusercontent.com/1892221/74308034-132d5480-4da2-11ea-9f22-cb8cc377f2fd.jpg)

**Comment by Elderry** [comment]
顺带一提，杭州管控的严么，要不是我被隔离在家，也不会跑来跟你挑这么细的问题😜

**Comment by EnixCoda** [comment]
挺严的
Good luck!

**Comment by EnixCoda** [comment]
Closing this due to no following thumb ups.

Comments are still open.
