### ISSUE TITLE
Can not open file page in firefox

### ISSUE THREAD

**Issue by MisLink** [EnixCoda/Gitako#48]
OS: MacOS 10.14.6
Firefox: 73.0

The webpage is loading forever when clicking file link in Gitako sidebar, and nothing output to dev tool.

**Comment by EnixCoda** [comment]
Hi @MisLink 
Thank you for your feedback, I'll fix it ASAP.

**Comment by EnixCoda** [comment]
Hi @MisLink 
This issue has been resolved at version `v0.8.8`.
Please upgrade Gitako and give a try!

**Comment by MisLink** [comment]
It works! Thanks for your hard work
