### ISSUE TITLE
[Feature request] Filter the tree view when in a pull-request to only those files.

### ISSUE THREAD

**Issue by NickDrouin** [EnixCoda/Gitako#52]
Feature request: Filter the tree view when in a pull-request to only those files.

**Comment by jmredfern** [comment]
This would be very useful!

**Comment by EnixCoda** [comment]
Done. Please give a try on `v2.1.0`. 

There are few details could be improved in later iterations, e.g.
1. Expand all folders in PR by default
1. Show diff stats
1. Show file status(add/edit/delete)

**Comment by maliming** [comment]
hi @EnixCoda 

We have to consider the case of paging when PR changes a lot.

```http
GET /repos/:owner/:repo/pulls/:pull_number/files
```
https://developer.github.com/v3/pulls/#list-pull-requests-files

>Note: Responses include a maximum of 3000 files. The paginated response returns 30 files per page by default.


eg:
https://api.github.com/repos/EnixCoda/Gitako/pulls/23/files
https://api.github.com/repos/EnixCoda/Gitako/pulls/23/files?page=2

**Comment by EnixCoda** [comment]
hi @maliming, Thank you for your feedback. That is really a good point! I'll fix it soon.

It would be great if you or anyone else can give me a link to such PR containing that amount of changes so I can test before release.

**Comment by EnixCoda** [comment]
I misunderstood `Responses include a maximum of 3000 files`.

I thought when request without `page` param, the response returns no more than 3000 files. But in fact, the `page` param defaults to `1`. So it returns no more than 30 files without `page`.

For the `3000`, maybe it indicates that `page` should be no greater than 100 (3000/30)?

**Comment by EnixCoda** [comment]
Fixes for paging will be available in `v2.1.2` soon.

**Comment by NickDrouin** [comment]
Looking great, thanks for taking this.

**Comment by EnixCoda** [comment]
File tree will expand all folders automatically in PR page since `v2.3.0`.
