### ISSUE TITLE
[Feature] Update icons (and add option to customize?)

### ISSUE THREAD

**Issue by gabrielecanepa** [EnixCoda/Gitako#55]
What about removing the icon animation when a page loads and the tree is closed (I find it annoying 😅), and update the icon to show something more meaningful to the action? 

I did a small test, here it's how it would look (the icon is just to test, eventually in the future you could also add an option to select an octicon):

![gitako](https://user-images.githubusercontent.com/24722181/78453200-6c25b480-7690-11ea-8765-a5822b8e4f4d.gif)

Amazing job!!! 👏

**Comment by EnixCoda** [comment]
Hi @gabrielecanepa . Thanks for your feedback

The animation has been removed in c7403e5ad8c34b5b1514ecd054b90363f1853624

I'll leave this issue open for more requests for custom icons option :)

**Comment by EnixCoda** [comment]
Close as the icon has been replace with Gitako's logo.
