### ISSUE TITLE
能增加gitlab私服的支持吗？

### ISSUE THREAD

**Issue by AriaLyy** [EnixCoda/Gitako#57]
非常感谢作者提供了这么好的一个插件。
公司采用的是自己搭建的gitlab私服的方式，所以gitako就无法使用了。

**Comment by EnixCoda** [comment]
多谢你的赏识！

私服指的是 GitHub enterprise 对吗？已经开发得差不多了，因为改动较多，还在谨慎排查问题，顺利的话将于近期推出

related to #34

**Comment by EnixCoda** [comment]
另外关于 GitLab ，它似乎提供了内置的文件树，我不确定是不是还有必要支持它

**Comment by AriaLyy** [comment]
我查看了下配置，好像没有文件树，谷歌下，好像都是一些插件～～

**Comment by EnixCoda** [comment]
这里有个 2 年前的 plan，而且已经完成了

https://gitlab.com/gitlab-org/gitlab-foss/-/issues/31890

![image](https://user-images.githubusercontent.com/7480839/78867537-d749ff00-7a73-11ea-88dc-e2d0b1ca8458.png)

我找了一下，发现在 project 的页面可以看到如上图的若干按钮，通过点击 `Web IDE` 可以启用这一功能

我不确定有了这个功能的情况下还有多少必要让 Gitako 适配 GitLab。

想听听你的看法 @AriaLyy

**Comment by AriaLyy** [comment]
一直没注意，有那个web ide 应该就不需要文件树了，感谢作者🙏

**Comment by young1lin** [comment]
可以支持 Gitee 吗，我看访问国内的 Gitee 没任何反应。。

**Comment by EnixCoda** [comment]
@young1lin 请参照这里操作 https://github.com/EnixCoda/Gitako/wiki/Use-in-GitHub-enterprise-and-other-sites

**Comment by young1lin** [comment]
> @young1lin 请参照这里操作 https://github.com/EnixCoda/Gitako/wiki/Use-in-GitHub-enterprise-and-other-sites

感谢🙏👍
