### ISSUE TITLE
How to enlarge width

### ISSUE THREAD

**Issue by PandaFang** [EnixCoda/Gitako#6]
如何调整宽度, java 和 android 项目 文件夹层次太深了， 宽度不够看。

**Comment by EnixCoda** [comment]
你好，

目前对层级较多的项目的浏览体验暂未优化，会尽快加入 横向滚动条 或 必要时扩展宽度 的方案。

感谢你的使用！

**Comment by PandaFang** [comment]
像 Octotree 一样拖拉调整宽度比较好， 滚动条不方便

**Comment by EnixCoda** [comment]
Finished with 560a64d768270c78db81b2a698b0bdde32edf166
