### ISSUE TITLE
UX enhancements, remove gridline and padding, change X icon.

### ISSUE THREAD

**Issue by softveda** [EnixCoda/Gitako#63]
I am requesting a few enhancements

1. Remove the gridlines. The padding around the filename take too much space. It should be condensed to show more files without vertical scrolling.
2. The cross (X) button on the top right corner show/hide the navigation pane is not intuitive. Suggest to change the icon to push-pin as that is commonly used for docking/undocking panes.
3. Perhaps better show the branch name (e.g. master) with a git branch icon and not just like a sub-directory.

**Comment by rafi** [comment]
It would be wonderful to add a "compact/condensed" setting = no horizontal lines, and less top/bottom margin.

**Comment by sf-pear** [comment]
I would also love an option that was more compact and without the lines. Would be perfect if it looked like the VS Code sidebar! Wish I knew enough to contribute with the code for this one.
![image](https://user-images.githubusercontent.com/57198690/120931287-2bd92080-c6f1-11eb-9f52-2aebfdedc38d.png)

**Comment by EnixCoda** [comment]
@sf-pear Thank you :)

The code change required for applying this feature is very simple. The problem is about the design. I am hesitant to break the current design style from http://primer.style/.

I'll consider adding this as an optional feature (disabled by default) as so many users are asking for it.

**Comment by sf-pear** [comment]
@EnixCoda I made a little draft on Figma using the official components. Happy to help with design matters if you'd like, just let me know :) the padding is a bit off for the file tree, but that's the idea (it would be just a matter of removing the lines and making the padding a bit smaller from what it is now).
<img width="281" alt="gitako-sidebar" src="https://user-images.githubusercontent.com/57198690/121017055-233e2400-c79d-11eb-8fb9-0d8c203fc439.png">

**Comment by EnixCoda** [comment]
@sf-pear It is very generous of you and this is a very inspirational design! Thank you so much! 😁

**Comment by EnixCoda** [comment]
Good news! Compact mode is shipped in `v3.1.0`. You can enable it from settings.
