### ISSUE TITLE
[Feature request] Clear search results

### ISSUE THREAD

**Issue by pedrolamas** [EnixCoda/Gitako#65]
Would be great to have a button appearing on the search box that with a single click would clear the search results!

Right now we have to click inside the search box and delete the text - something not ideal when you are just using the mouse at that moment.

**Comment by EnixCoda** [comment]
Gitako is using components from [primer](https://primer.style/)

The TextInput component does not support adding buttons inside.

I'll make input content selected when search box is focused.
