### ISSUE TITLE
Hide empty middle packages

### ISSUE THREAD

**Issue by xuchuanyin** [EnixCoda/Gitako#7]
In java/scala projects, the package path is long.
It will be great to hide the empty middle packages/directories.

For example, in Gitako project, it will display
```
-- src
---- asserts/icons
-------- Gitako.jpg
```
instead of
```
-- src
---- asserts
-------- icons
------------ Gitako.jpg
```

**Comment by EnixCoda** [comment]
Hi @xuchuanyin ,
Thank you for your advice. This feature looks very helpful and necessary.
I'll implement it!

**Comment by EnixCoda** [comment]
GitHub wiki page doesn't support uploading images.
So I have put images of this feature here.

| disabled | enabled |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/7480839/41818195-2f869f08-77dc-11e8-8690-9818b5df6a37.png) | ![image](https://user-images.githubusercontent.com/7480839/41818179-c00751d6-77db-11e8-89bc-4ddbcf4a9bfd.png) |

It'll be released soon.

**Comment by EnixCoda** [comment]
It's now released!
It is not enabled by default. You can enable it in settings. @xuchuanyin 
Let me know if there is any issue. Enjoy it!
