### ISSUE TITLE
[bug] Gitako moves the profile buttons

### ISSUE THREAD

**Issue by aminya** [EnixCoda/Gitako#70]
Currently:
![image](https://user-images.githubusercontent.com/16418197/84420769-216c6f80-abe0-11ea-80d7-6a1ec8ea91d1.png)

Expected:
![image](https://user-images.githubusercontent.com/16418197/84420811-347f3f80-abe0-11ea-80e9-ea4ccb3daf63.png)

**Comment by EnixCoda** [comment]
#47 This was made as a feature.

I'll think of alternative methods when updating design of Gitako's toggle button.
