### ISSUE TITLE
download files

### ISSUE THREAD

**Issue by Nayacco** [EnixCoda/Gitako#72]
Is it possible to add a download feature?

**Comment by EnixCoda** [comment]
Hi, @GoldSubmarine

Could you provide more details on that? like
- When and why do you download files?
- What kind of files are they?
- Would you like to download files before navigating to the files' page?
- Do you download lots of files? Or perhaps what you need is to copy the file's content (which Gitako already supports)?

**Comment by Nayacco** [comment]
Sometimes i want to download some files or a folder, not the whole repo, so i want the feature like [gitzip-for-github](https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn)

Maybe i can choose some files from the navigation on the left, and download them.

**Comment by lizhuoyuan** [comment]
I want too ~

**Comment by yidasanqian** [comment]
@EnixCoda  Need this feature too

**Comment by kidonng** [comment]
For downloading specific files, when #73 landed you can Alt + click to achieve that.
For downloading folders, you can already use the aforementioned gitzip. Refined GitHub also has integration with https://github.com/download-directory.

**Comment by EnixCoda** [comment]
Closing. Now the open raw content feature is available via file tree context menu.
