### ISSUE TITLE
Gitako Not Working

### ISSUE THREAD

**Issue by AriefLuthfi79** [EnixCoda/Gitako#77]
I love gitako, this is amazing project but nowadays gitako not working properly, any idea for this?

**Comment by EnixCoda** [comment]
Hi, @AriefLuthfi79 Thank you for the feedback!

Gitako relies on specific DOM elements to resolve environments(GitHub, Gitee, etc). It seems that GitHub has updated its DOM today and some specific elements have been replaced.

I'll release a patch ASAP!

**Comment by EnixCoda** [comment]
Fixed. `v2.1.3` is under review. It should be publicly available soon!

**Comment by AriefLuthfi79** [comment]
Thanks @EnixCoda, your project help us a lot :)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I have experienced the same problem and found this issue. Waiting for the update.

**Comment by EnixCoda** [comment]
`v2.1.3` is available to Firefox and Chrome now.

Let's keep this issue open until most users are updated.

**Comment by AriaLyy** [comment]
edge浏览器的啥时候更新？

**Comment by EnixCoda** [comment]
@AriaLyy 根据以往的审核速度，需要1-2周。需要的话可以暂时从 [release](https://github.com/EnixCoda/Gitako/releases/tag/v2.1.3) 手动安装使用。

---
For Edge users, the Edge extension store usually takes 1-2 weeks to review. You can download it from the [release page](https://github.com/EnixCoda/Gitako/releases/tag/v2.1.3) and install it manually.

**Comment by AriaLyy** [comment]
@EnixCoda 好像现在gitee上无法使用了，我手动安装了最新版本，github是可以了，但是gitee图标还是没有显示出来

**Comment by AriaLyy** [comment]
好像可以了，为啥gitee不是默认打开的？还需要手动打开。。默认打开网站建议增加gitee
![image](https://user-images.githubusercontent.com/10437293/87867899-09002980-c9c4-11ea-8a38-c1d27beeed35.png)

**Comment by EnixCoda** [comment]
@AriaLyy 那需要修改插件权限（增加新的域名），会令所有用户的 Gitako 被自动禁用，考虑到 Gitee 上的用户量不大，我不打算贸然调整。

**Comment by lohithgn** [comment]
Hi.
I am on Edge Microsoft Edge - Version 84.0.522.40 (Official build) (64-bit).
I notice 2.1.3 is available for Chrome & FF. Any idea when we can get 2.1.3 for Edge ?

**Comment by EnixCoda** [comment]
Hi @lohithgn 
> For Edge users, the Edge extension store usually takes 1-2 weeks to review. You can download it from the release page and install it manually.

**Comment by lohithgn** [comment]
@EnixCoda ahh i see. thanks.

**Comment by lohithgn** [comment]
@EnixCoda looks like Edge has got the 2.1.3 update. i am able to get the tree now.
Thanks.
![image](https://user-images.githubusercontent.com/2450336/88034889-e876d180-cb73-11ea-9b4c-9ec7a9596631.png)

**Comment by EnixCoda** [comment]
@lohithgn Great, it is the quickest review so far.

**Comment by AriefLuthfi79** [comment]
@EnixCoda u want to closed this buddy?, it think no more buggy

**Comment by EnixCoda** [comment]
![image](https://user-images.githubusercontent.com/7480839/89103235-daae2f80-d442-11ea-8540-1e1c4faaa378.png)

Yeah, almost all users have updated. Thanks for reminding!
