### ISSUE TITLE
GitHub's navbar may look weird when Gitako is open and the viewport is not wide enough

### ISSUE THREAD

**Issue by EnixCoda** [EnixCoda/Gitako#78]
- It could be empty.
- It could show a scrollbar which does not look neat.

But I have not figured out a way to make it perfect yet. The style rules of GitHub's are too complex, which are full of `!important` and may change between different nav tabs.

However, I did not break the navbar's functionalities, all the items are still accessible to users.

**Comment by maliming** [comment]
The navigation of the repository also sometime look weird on a wide screen. : )

![image](https://user-images.githubusercontent.com/6908465/88146442-72837080-cc2e-11ea-81f9-948b333ee19f.png)

![image](https://user-images.githubusercontent.com/6908465/88146552-9e065b00-cc2e-11ea-830b-081d36d5bbf3.png)

**Comment by EnixCoda** [comment]
Added option to disable shrinking navbar in `v2.2.0`

**Comment by EnixCoda** [comment]
`v2.2.0` is out and shrinking the navbar is disabled by default.
