### ISSUE TITLE
[Feature request] Recursive node toggling

### ISSUE THREAD

**Issue by mykiwi** [EnixCoda/Gitako#81]
Hi,

Firstly, thanks for this awesome extension!

One feature that could be nice is to be able to expand/close recursively, based on CTRL+click for example.

For now, we must open everything one by one. example:
![](https://i.imgur.com/iS2j0aN.gif)

What would be nice is when we would do a CTRL + click, it would expand/close everything. example:
![](https://i.imgur.com/zaJABz4.gif)

What do you think?

**Comment by EnixCoda** [comment]
Thank you for this suggestion! It should be quite useful.

**Comment by EnixCoda** [comment]
Done in `v2.3.0`. I picked `shift` and `alt` keys for this feature as `ctrl` or `command` both have important default behaviors on macOS or Windows. Users can change their preferences (between `shift` and `alt`) in the settings panel.

**Comment by EnixCoda** [comment]
Should folders toggle recursively when navigating with keyboard control? 🤔

**Comment by mykiwi** [comment]
Thanks, `shift+click` works well :+1: 
I don't really use keyboard navigation, so up to you

**Comment by EnixCoda** [comment]
Added keyboard supports in `v2.4.1`
