### ISSUE TITLE
[Feature] Remember the toggle status of the repository.

### ISSUE THREAD

**Issue by maliming** [EnixCoda/Gitako#83]
Maybe Gitako should save the state of the repository rather than a global `open/close` state. 👍 
```
https://github.com/EnixCoda/Gitako => open
https://github.com/EnixCoda/safe-touch = > close
```

**Comment by vivekragunathan** [comment]
Does that mean that there is global open/close state? 🤔  .. which is what I was looking for. But does not work for me on Chrome.

**Comment by EnixCoda** [comment]
@VivekRagunathan You can disable `Auto expand` ~`Auto toggle according to page content.`~ to activate global open/close state
