### ISSUE TITLE
[Feature request] Knob for controlling font size in the tree view

### ISSUE THREAD

**Issue by onethirdzero** [EnixCoda/Gitako#86]
Zooming out of the page (`ctrl + -`) is somewhat of a workaround, but that shrinks the font on the rest of the page too.

Would be nice if we could shrink or enlarge the font according to our preferences! I find that the current font size is too large for my liking.

**Comment by mmmkkaaayy** [comment]
+1

My first impression upon moving to this from OctoTree was that the font size and padding (top/bottom padding on every row, and padding-left on children) are using more screen real estate than desired.

**Comment by EnixCoda** [comment]
Hi @onethirdzero 
As the compact layout option (in the settings -> file tree section) is available now, is this still an issue for you?

**Comment by onethirdzero** [comment]
@EnixCoda That is much nicer. No longer an issue for me. Thanks for the update!
