### ISSUE TITLE
[Bug] Jump to doesnt work. Wrong href with no #id

### ISSUE THREAD

**Issue by razbensimon** [EnixCoda/Gitako#88]
For example here
https://github.com/facebook/create-react-app/pull/4964/files

Not all the file tree links have good URL. some of them missing the #id 
On the picture below, see the bottom left corner - you can see the broken link when I hover it.

![image](https://user-images.githubusercontent.com/5955905/95387257-24127380-08f9-11eb-97d4-18f3d65dc0b1.png)

**Comment by EnixCoda** [comment]
Thank you! @razbensimon

**Comment by EnixCoda** [comment]
It is because the API Gitako currently uses to fetch the files of PR responded with unexpected result. Not sure about the deeper reason, maybe there is git commit SHA-1 collision?

However, I've found a new way to fetch file lists while not in the `files` tab which should work better.

**Comment by razbensimon** [comment]
Thanks, waiting for the new version :)

**Comment by EnixCoda** [comment]
Fixed in `v2.4.1`
