### ISSUE TITLE
Git source file link start with "#" symbol

### ISSUE THREAD

**Issue by poplax** [EnixCoda/Gitako#91]
Git source file (file name starts with "#") link starts with "#" symbol, clicking will not go to the corresponding page.

**Comment by EnixCoda** [comment]
Thanks for the feedback. Could you provide the link for reproducing in #88 ?

**Comment by poplax** [comment]
Yes
https://github.com/SwiftOldDriver/iOS-Weekly/tree/master/Reports/2020#135-2020.11.09.md

**Comment by EnixCoda** [comment]
I see. So this is not about the same issue as #88 

Will fix it soon.

**Comment by EnixCoda** [comment]
Fixed in `v2.4.1`
