### ISSUE TITLE
[Feature] Hide current Gitako version at the bottom

### ISSUE THREAD

**Issue by acbetter** [EnixCoda/Gitako#93]
总觉得这个 v2.4.0 很出戏，感觉设置按钮也可以移到上边，简洁些

![image](https://user-images.githubusercontent.com/13360124/98345325-7a391a80-204f-11eb-8a83-62b2911987fc.png)

**Comment by EnixCoda** [comment]
感谢反馈！

这是基于如下考虑特意设计的：
- 如果有更新的话，可以让用户更敏感地察觉
- 作为查看更新记录的入口，了解新功能/修复的缺陷

也许可以考虑把版本号放到设置界面中展示，但将设置按钮移到顶部的话我暂时没有想到好的布局方案

**Comment by EnixCoda** [comment]
版本号与文件名的文本颜色对比度自 `v2.5.0` 起已显著增加，一定程度上避免了该问题
暂且关闭此 issue
