### ISSUE TITLE
[Feature] 希望可以加入是否每次打开仓库都自动展开面板的选项

### ISSUE THREAD

**Issue by huohaodong** [EnixCoda/Gitako#95]
每次进入仓库的时候，左边面板都会自动打开，对于我个人而言不太习惯，我想也有人会和我一样，希望能添加一个**是否进入仓库自动展开面板**的选项。

**Comment by EnixCoda** [comment]
设置中的 `Auto toggle according to page content.` 是否满足你的需求？🤔

**Comment by EnixCoda** [comment]
我觉得产生这个 issue 的深层原因是 目前的说明不够清晰，我会思考如何更好地说明功能，感谢！

**Comment by huohaodong** [comment]
是的，尴尬了，我一开始以为那个选项只是说会根据某些页面内容大小自适应展开/收缩面板，确实那个选项可以满足我的需求。顺带一提，这个扩展目前使用下来体验很棒，感谢作者提供了这么好的东西让大家使用。

**Comment by EnixCoda** [comment]
很荣幸！ 😄
