### ISSUE TITLE
[Feature request] Compatible with OctoLinker

### ISSUE THREAD

**Issue by chawyehsu** [EnixCoda/Gitako#97]
> [OctoLinker](https://octolinker.now.sh/) is is a browser extension for GitHub, that turns language-specific statements like include require or import into links.

OctoLinker can't transform links of files clicked and opened from Gitako currently.

|Expected|Acutal|
|-|-|
|![Expected](https://user-images.githubusercontent.com/5764917/98500169-b99d7c00-2286-11eb-8eb0-cf8506c80de1.png)|![Acutal](https://user-images.githubusercontent.com/5764917/98500157-a8ed0600-2286-11eb-9a1b-849088ac65bb.png)|

I don't know whether should I file the request here or in OctoLinker's repo. But this might need a co-work I guess.

**Comment by EnixCoda** [comment]
Hi @chawyehsu 

Gitako emits `pjax:ready` event to ~`window`~ `document` after mutating page content for redirection. Maybe OctoLinker could listen to the event (or events related to the history API, e.g. `pushstate`) and do its work again to fix this issue.

**Comment by chawyehsu** [comment]
@EnixCoda 

OctoLinker did listen to [the native `pjax:end` event](https://github.com/OctoLinker/injection/blob/0e34e2aeed1a2d80bf585eacc9734a7e96f217af/index.js#L12). I didn't dive into the detail but I suppose Gitako could have it. Octotree had the same issue before and they fixed it.

references:
- https://github.com/OctoLinker/OctoLinker/issues/416
- https://github.com/ovity/octotree/issues/490
- https://github.com/sindresorhus/refined-github/issues/1759
- https://github.com/ovity/octotree/pull/861
- https://github.com/ovity/octotree/blob/3f6e59e969/src/adapters/pjax.js

**Comment by EnixCoda** [comment]
That's really detailed guidances to the issue, thanks!

Gitako does emit native events. I'll discuss with OctoLinker's maintainers to see if they'd adopt Gitako's events.

**Comment by EnixCoda** [comment]
It turns out to be harder to fix than I expected.

If Gitako emits the `pjax:end` event like Octotree, there will be problems with navigating back. Did not check if octotree also have same problems. Will see what I can do later.

**Comment by kidonng** [comment]
If I understand correctly, Octotree doesn't have navigation issues.

`pjax:end` is where the page load fully ends and most extensions/user scripts (such as Refined GitHub) listen to this event, so if Gitako doesn't fire this event, it may be incompatible with lots of things.

**Comment by EnixCoda** [comment]
> it may be compatible with lots of things.

@kidonng I'm afraid you are right.

Gitako depends on [PJAX-API](https://github.com/falsandtru/pjax-api) for PJAX features. And its author did warn me about having multiple PJAX instances on the same page could cause troubles, especially when they follow different conventions. With PJAX-API, Gitako could navigate really fast but also experience some new troubles, including this one. **I do respect PJAX-API and its author, no offense.**

Maybe it is time to implement another PJAX lib by myself to fix this. 😶

**Comment by EnixCoda** [comment]
Should have been fixed in v2.4.3.
