### ISSUE TITLE
[Feature] Add pin button to toggle hover Gitako over other contents

### ISSUE THREAD

**Issue by Higurashi-kagome** [EnixCoda/Gitako#98]
很好的扩展！⭐️

有几个建议：

- 希望在进入项目时不直接弹出文件目录而是在侧边显示插件 logo

- 希望像 Octotree 那样在点击 logo 时从侧边**弹出**而不影响 GitHub 显示（除非在侧边固定住）

**Comment by EnixCoda** [comment]
谢谢！

> 希望在进入项目时不直接弹出文件目录而是在侧边显示插件 logo

⚙️ Settings -> Auto toggle according to page content. 取消此处勾选将记忆启闭状态、不再自动弹出

另外我会仔细斟酌是否应支持“弹出”布局

**Comment by Higurashi-kagome** [comment]
Thanks!🤝

**Comment by kidonng** [comment]
I'd also like Gitako to support "Floating mode" like Octotree, which enables e.g. hover to open and no more [layout shifting](https://web.dev/cls/).

**Comment by EnixCoda** [comment]
v3.0.0 is out with this change :D

**Comment by kidonng** [comment]
You are Awesome 😎
